<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="FP_Form.Controller.formdesign" %>
<%@ Import namespace="System.Collections.Generic" %>
<%@ Import namespace="FangPage.Common" %>
<%@ Import namespace="FangPage.MVC" %>
<%@ Import namespace="FP_Form" %>
<%@ Import namespace="FP_Form.Model" %>
<%@ Import namespace="FangPage.WMS" %>
<%@ Import namespace="FangPage.WMS.Model" %>
<%@ Import namespace="FangPage.WMS.Bll" %>
<script runat="server">
protected override void View()
{
	base.View();
	ViewBuilder.Append("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd\">\r\n");
	ViewBuilder.Append("<html>\r\n");
	ViewBuilder.Append("<head>\r\n");
	ViewBuilder.Append("<meta content=\"text/html; charset=utf-8\" http-equiv=\"content-type\">\r\n");
	ViewBuilder.Append("<title>表单智能设计器</title>\r\n");
	ViewBuilder.Append("	" + echo(meta) + "\r\n");
	ViewBuilder.Append("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
	ViewBuilder.Append("<meta name=\"renderer\" content=\"webkit\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/bootstrap.css\">\r\n");
	ViewBuilder.Append("<!--[if lte IE 6]>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/bootstrap-ie6.css\">\r\n");
	ViewBuilder.Append("<![endif]-->\r\n");
	ViewBuilder.Append("<!--[if lte IE 7]>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/ie.css\">\r\n");
	ViewBuilder.Append("<![endif]-->\r\n");
	ViewBuilder.Append("<style type=\"text/css\">\r\n");
	ViewBuilder.Append("    .TableHeader { COLOR:#2E2E5A; FONT-WEIGHT: bold; FONT-SIZE: 9pt; background:url(statics/images/list_hd_bg.png); line-height:21px;}\r\n");
	ViewBuilder.Append("    .big { font-size: 12pt;}\r\n");
	ViewBuilder.Append("    .small  { font-size: 9pt;}\r\n");
	ViewBuilder.Append("</style>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" charset=\"utf-8\" src=\"formdesign/jquery-1.7.2.min.js?2023\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap.min.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<link type=\"text/css\" href=\"" + echo(plupath) + "layer/skin/layer.css\" rel=\"stylesheet\" id=\"skinlayercss\">\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "layer/layer.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "datepicker/WdatePicker.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\">\r\n");
	ViewBuilder.Append("    function myclose() {\r\n");
	ViewBuilder.Append("        if (confirm(\"您确定要关闭表单设计器吗？\")) {\r\n");
	ViewBuilder.Append("            window.close();\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("</");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("</head>\r\n");
	ViewBuilder.Append("<body class=\"bodycolor\">\r\n");
	ViewBuilder.Append("    <table width=\"100%\" height=\"100%\" class=\"big\" bgcolor=\"#000000\" border=\"0\" cellpadding=\"3\" cellspacing=\"1\" align=\"center\">\r\n");
	ViewBuilder.Append("        <tr bgcolor=\"#DDDDDD\">\r\n");
	ViewBuilder.Append("            <td class=\"TableHeader\" colspan=\"2\" height=\"20\">\r\n");
	ViewBuilder.Append("                <span class=\"small\">表单名称：" + echo(forminfo.name) + "</span>\r\n");
	ViewBuilder.Append("            </td>\r\n");
	ViewBuilder.Append("        </tr>\r\n");
	ViewBuilder.Append("        <tr style=\"background:#DDDDDD;\">\r\n");
	ViewBuilder.Append("            <td width=\"100%\" valign=\"top\">\r\n");
	ViewBuilder.Append("                <form action=\"\" method=\"post\" id=\"frmpost\" name=\"frmpost\">\r\n");
	ViewBuilder.Append("                <script id=\"myFormDesign\" type=\"text/plain\" style=\"width:100%;height:auto;*height:100%;\">\r\n");
	ViewBuilder.Append("                    " + echo(forminfo.content) + "\r\n");
	ViewBuilder.Append("                </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("                </form>\r\n");
	ViewBuilder.Append("            </td>\r\n");
	ViewBuilder.Append("            <td style=\"background:#ffffff\" valign=\"top\" align=\"center\">\r\n");
	ViewBuilder.Append("                <table width=\"120\" border=\"0\" cellspacing=\"1\" class=\"small\" bgcolor=\"#000000\" cellpadding=\"3\" align=\"center\">\r\n");
	ViewBuilder.Append("                    <tr class=\"TableHeader\" style=\"height:30px;\">\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            表单控件\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr>\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn\" style=\"width:130px; text-align: left\" onclick=\"leipiFormDesign.exec('text');\">\r\n");
	ViewBuilder.Append("                            <img src=\"statics/form/textfield.gif\" align=\"absmiddle\">单行文本框</button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr>\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn\" style=\"width:130px; text-align: left\" onclick=\"leipiFormDesign.exec('textarea');\">\r\n");
	ViewBuilder.Append("                            <img src=\"statics/form/textarea.gif\" align=\"absmiddle\">多行文本框</button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr>\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn\" style=\"width:130px;text-align: left\" onclick=\"leipiFormDesign.exec('select');\">\r\n");
	ViewBuilder.Append("                            <img src=\"statics/form/listmenu.gif\" align=\"absmiddle\">下拉选择框</button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr>\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn\" style=\"width:130px;text-align: left\" onclick=\"leipiFormDesign.exec('checkbox');\">\r\n");
	ViewBuilder.Append("                            <img src=\"statics/form/checkbox.gif\" align=\"absmiddle\">&nbsp;复选择框</button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr>\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn\" style=\"width:130px; text-align: left\" onclick=\"leipiFormDesign.exec('sign');\">\r\n");
	ViewBuilder.Append("                            <img src=\"statics/form/sign.png\" style=\"width:20px;height:20px;\" align=\"absmiddle\">会签控件</button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr>\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn\" style=\"width:130px; text-align: left\" onclick=\"leipiFormDesign.exec('calendar');\">\r\n");
	ViewBuilder.Append("                            <img src=\"statics/form/calendar.gif\" style=\"width:20px;height:20px;\" align=\"absmiddle\">日期控件</button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr>\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn\" style=\"width:130px; text-align: left\" onclick=\"leipiFormDesign.exec('title');\">\r\n");
	ViewBuilder.Append("                            <img src=\"statics/form/title.png\" style=\"width:20px;height:20px;\" align=\"absmiddle\">标题控件</button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr>\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn\" style=\"width:130px; text-align: left\" onclick=\"leipiFormDesign.exec('upload');\">\r\n");
	ViewBuilder.Append("                            <img src=\"statics/form/attach.png\" style=\"width:20px;height:20px;\" align=\"absmiddle\">上传控件</button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                </table>\r\n");
	ViewBuilder.Append("                <br>\r\n");
	ViewBuilder.Append("                <table width=\"120\" border=\"0\" cellspacing=\"1\" class=\"small\" bgcolor=\"#000000\" cellpadding=\"3\" align=\"center\">\r\n");
	ViewBuilder.Append("                    <tr class=\"TableHeader\" style=\"height:30px;\">\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            表单操作\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr class=\"TableHeader\">\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn btn-success\" style=\"width: 130px; height: 30px; text-align: center\" onclick=\"leipiFormDesign.fnCheckForm()\">\r\n");
	ViewBuilder.Append("                            <b>保存表单</b></button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr class=\"TableHeader\">\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn btn-success\" style=\"width: 130px; height: 30px; text-align: center\" onclick=\"leipiFormDesign.fnReview()\">\r\n");
	ViewBuilder.Append("                            <b>表单预览</b></button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr class=\"TableHeader\">\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn btn-success\" style=\"width: 130px; height: 30px; text-align: center\" onclick=\"leipiFormDesign.fnImport()\">\r\n");
	ViewBuilder.Append("                            <b>导入表单</b></button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr class=\"TableHeader\">\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn btn-success\" style=\"width: 130px; height: 30px; text-align: center\" onclick=\"leipiFormDesign.fnCheckForm()\">\r\n");
	ViewBuilder.Append("                            <b>导出表单</b></button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                    <tr class=\"TableHeader\">\r\n");
	ViewBuilder.Append("                        <td align=\"center\">\r\n");
	ViewBuilder.Append("                            <button class=\"btn btn-success\" style=\"width: 130px; height: 30px; text-align: center\" onclick=\"myclose()\">\r\n");
	ViewBuilder.Append("                            <b>关闭设计器</b></button>\r\n");
	ViewBuilder.Append("                        </td>\r\n");
	ViewBuilder.Append("                    </tr>\r\n");
	ViewBuilder.Append("                </table>\r\n");
	ViewBuilder.Append("            </td>\r\n");
	ViewBuilder.Append("        </tr>\r\n");
	ViewBuilder.Append("    </table>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" charset=\"utf-8\" src=\"formdesign/ueditor/ueditor.config.js?2023\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" charset=\"utf-8\" src=\"formdesign/ueditor/ueditor.all.js?2023\"> </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" charset=\"utf-8\" src=\"formdesign/ueditor/lang/zh-cn/zh-cn.js?2023\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" charset=\"utf-8\" src=\"formdesign/ueditor/formdesign/leipi.formdesign.v4.js?2023\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<!-- script start-->  \r\n");
	ViewBuilder.Append("<script type=\"text/javascript\">\r\n");
	ViewBuilder.Append("    var leipiEditor = UE.getEditor('myFormDesign', {\r\n");
	ViewBuilder.Append("        allowDivTransToP: false,//阻止转换div 为p\r\n");
	ViewBuilder.Append("        toolleipi: true,//是否显示，设计器的 toolbars\r\n");
	ViewBuilder.Append("        textarea: 'design_content',\r\n");
	ViewBuilder.Append("        //这里可以选择自己需要的工具按钮名称,此处仅选择如下五个\r\n");
	ViewBuilder.Append("        toolbars: [[\r\n");
	ViewBuilder.Append("         'fullscreen', 'source', '|', 'undo', 'redo', '|', 'bold', 'italic', 'underline', 'fontborder', 'strikethrough', 'removeformat', '|', 'forecolor', 'backcolor', 'insertorderedlist', 'insertunorderedlist', '|', 'fontfamily', 'fontsize', '|', 'indent', '|', 'justifyleft', 'justifycenter', 'justifyright', 'justifyjustify', '|', 'link', 'unlink', '|', 'horizontal', 'spechars', 'wordimage', '|', 'inserttable', 'deletetable', 'mergecells', 'splittocells','|', 'image']],\r\n");
	ViewBuilder.Append("        //focus时自动清空初始化时的内容\r\n");
	ViewBuilder.Append("        //autoClearinitialContent:true,\r\n");
	ViewBuilder.Append("        //关闭字数统计\r\n");
	ViewBuilder.Append("        wordCount: false,\r\n");
	ViewBuilder.Append("        //关闭elementPath\r\n");
	ViewBuilder.Append("        elementPathEnabled: false,\r\n");
	ViewBuilder.Append("        autoHeight: true,\r\n");
	ViewBuilder.Append("        initialFrameHeight: 600\r\n");
	ViewBuilder.Append("        //更多其他参数，请参考ueditor.config.js中的配置项\r\n");
	ViewBuilder.Append("    });\r\n");
	ViewBuilder.Append("    var leipiFormDesign = {\r\n");
	ViewBuilder.Append("        /*执行控件*/\r\n");
	ViewBuilder.Append("        exec: function (method) {\r\n");
	ViewBuilder.Append("            leipiEditor.execCommand(method);\r\n");
	ViewBuilder.Append("        },\r\n");
	ViewBuilder.Append("        /*type  =  save 保存设计 versions 保存版本  close关闭 */\r\n");
	ViewBuilder.Append("        fnCheckForm: function (type) {\r\n");
	ViewBuilder.Append("            if (leipiEditor.queryCommandState('source'))\r\n");
	ViewBuilder.Append("                leipiEditor.execCommand('source');//切换到编辑模式才提交，否则有bug\r\n");
	ViewBuilder.Append("            if (leipiEditor.hasContents()) {\r\n");
	ViewBuilder.Append("                leipiEditor.sync();/*同步内容*/\r\n");
	ViewBuilder.Append("                //获取表单设计器里的内容\r\n");
	ViewBuilder.Append("                var formid=" + echo(id) + ";\r\n");
	ViewBuilder.Append("                var formeditor = leipiEditor.getContent();\r\n");
	ViewBuilder.Append("                //异步提交数据\r\n");
	ViewBuilder.Append("                $.ajax({\r\n");
	ViewBuilder.Append("                    type: 'POST',\r\n");
	ViewBuilder.Append("                    url: 'formsave.aspx',\r\n");
	ViewBuilder.Append("                    dataType : 'json',\r\n");
	ViewBuilder.Append("                    data: { 'id': formid, 'design_content': formeditor },\r\n");
	ViewBuilder.Append("                    success: function (data) {\r\n");
	ViewBuilder.Append("                      if(data.success==1){\r\n");
	ViewBuilder.Append("                          $('#submitbtn').button('reset');\r\n");
	ViewBuilder.Append("                          layer.msg('表单保存成功！', 2, 1);\r\n");
	ViewBuilder.Append("                      }else{\r\n");
	ViewBuilder.Append("                          alert('表单保存失败！');\r\n");
	ViewBuilder.Append("                      }\r\n");
	ViewBuilder.Append("                    }\r\n");
	ViewBuilder.Append("                });\r\n");
	ViewBuilder.Append("            } else {\r\n");
	ViewBuilder.Append("                alert('表单内容不能为空！')\r\n");
	ViewBuilder.Append("                $('#submitbtn').button('reset');\r\n");
	ViewBuilder.Append("                return false;\r\n");
	ViewBuilder.Append("            }\r\n");
	ViewBuilder.Append("        },\r\n");
	ViewBuilder.Append("        /*预览表单*/\r\n");
	ViewBuilder.Append("        fnReview: function () {\r\n");
	ViewBuilder.Append("            if (leipiEditor.queryCommandState('source'))\r\n");
	ViewBuilder.Append("                leipiEditor.execCommand('source');/*切换到编辑模式才提交，否则部分浏览器有bug*/\r\n");
	ViewBuilder.Append("            if (leipiEditor.hasContents()) {\r\n");
	ViewBuilder.Append("                leipiEditor.sync();       /*同步内容*/\r\n");
	ViewBuilder.Append("                //获取表单设计器里的内容\r\n");
	ViewBuilder.Append("                var formid=" + echo(id) + ";\r\n");
	ViewBuilder.Append("                var formeditor = leipiEditor.getContent();\r\n");
	ViewBuilder.Append("                //异步提交数据\r\n");
	ViewBuilder.Append("                $.ajax({\r\n");
	ViewBuilder.Append("                    type: 'POST',\r\n");
	ViewBuilder.Append("                    url: 'formsave.aspx',\r\n");
	ViewBuilder.Append("                    dataType : 'json',\r\n");
	ViewBuilder.Append("                    data: { 'id': formid, 'design_content': formeditor },\r\n");
	ViewBuilder.Append("                    success: function (data) {\r\n");
	ViewBuilder.Append("                        if(data.success==1){\r\n");
	ViewBuilder.Append("                            window.open('formpreview.aspx?id=" + echo(id) + "', 'mywin', \"menubar=0,toolbar=0,status=0,resizable=1,left=0,top=0,scrollbars=1,width=\" + (screen.availWidth - 10) + \",height=\" + (screen.availHeight - 50) + \"\\\"\");\r\n");
	ViewBuilder.Append("                        }else{\r\n");
	ViewBuilder.Append("                            alert('对不起，表单保存不成功，预览失败！');\r\n");
	ViewBuilder.Append("                        }\r\n");
	ViewBuilder.Append("                    }\r\n");
	ViewBuilder.Append("                });\r\n");
	ViewBuilder.Append("            } else {\r\n");
	ViewBuilder.Append("                alert('表单内容不能为空！');\r\n");
	ViewBuilder.Append("                return false;\r\n");
	ViewBuilder.Append("            }\r\n");
	ViewBuilder.Append("        },\r\n");
	ViewBuilder.Append("        /*导入表单*/\r\n");
	ViewBuilder.Append("        fnImport: function () {\r\n");
	ViewBuilder.Append("          alert('sssssss');\r\n");
	ViewBuilder.Append("          $.layer({\r\n");
	ViewBuilder.Append("            type: 2,\r\n");
	ViewBuilder.Append("            shade: [0],\r\n");
	ViewBuilder.Append("            fix: false,\r\n");
	ViewBuilder.Append("            title: 'ssssssssssssssssssssssss',\r\n");
	ViewBuilder.Append("            maxmin: false,\r\n");
	ViewBuilder.Append("            iframe: { src:\"dddddddddddddddddddddd\"},\r\n");
	ViewBuilder.Append("            area: [widths, heights]\r\n");
	ViewBuilder.Append("          });\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("    };\r\n");
	ViewBuilder.Append("</");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("</body>\r\n");
	ViewBuilder.Append("</html>\r\n");
	if(iswrite==0)
	{
	Response.Write(ViewBuilder.ToString());
	}
	else if(iswrite==1)
	{
	Hashtable hash = new Hashtable();
	hash["errcode"] = 0;
	hash["errmsg"] ="";
	hash["html"]=ViewBuilder.ToString();
	FPResponse.WriteJson(hash);
	}
}
</script>
