<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="FP_WorkFlow.Controller.flowform" %>
<%@ Import namespace="System.Collections.Generic" %>
<%@ Import namespace="FangPage.Common" %>
<%@ Import namespace="FangPage.MVC" %>
<%@ Import namespace="FP_WorkFlow" %>
<%@ Import namespace="FP_WorkFlow.Model" %>
<%@ Import namespace="FangPage.WMS.Model" %>
<%@ Import namespace="FangPage.WMS.Bll" %>
<script runat="server">
protected override void View()
{
	base.View();
	ViewBuilder.Append("<!DOCTYPE html>\r\n");
	ViewBuilder.Append("<html>\r\n");
	ViewBuilder.Append("<head>\r\n");
	ViewBuilder.Append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
	ViewBuilder.Append("<title>表单处理</title>\r\n");
	ViewBuilder.Append("	" + echo(meta) + "\r\n");
	ViewBuilder.Append("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
	ViewBuilder.Append("<meta name=\"renderer\" content=\"webkit\">\r\n");
	ViewBuilder.Append("<link href=\"" + echo(plupath) + "bootstrap/css/bootstrap.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
	ViewBuilder.Append("<link href=\"" + echo(plupath) + "bootstrap/css/bootstrap-notify.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
	ViewBuilder.Append("<link href=\"" + echo(plupath) + "bootstrap/css/bootstrap-modal.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
	ViewBuilder.Append("<link href=\"" + echo(plupath) + "bootstrap/css/bootstrap-file-selector.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
	ViewBuilder.Append("<link href=\"" + echo(plupath) + "bootstrap/css/icomoon.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "jquery/jquery.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "nicescroll/jquery.nicescroll.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "bootstrap/js/bootstrap.bootbox.min.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "bootstrap/js/bootstrap.notify.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "bootstrap/js/bootstrap-prompts.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "bootstrap/js/bootstrap-modal.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "bootstrap/js/bootstrap-modalmanager.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "multifile/jquery.multifile.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "jform/jquery.form.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "modernizr/modernizr-2.6.1.min.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"/oa/public/js/util.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"/oa/public/js/form.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"/oa/public/js/attachment.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<link href=\"" + echo(plupath) + "uploadify/uploadify.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "uploadify/jquery.uploadify.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<link href=\"/oa/public/css/fp-bootstrap.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
	ViewBuilder.Append("<link href=\"" + echo(plupath) + "kindeditor/themes/default/default.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "kindeditor/kindeditor-min.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "kindeditor/lang/zh_CN.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<link href=\"" + echo(plupath) + "layer/skin/layer.css\" type=\"text/css\" rel=\"stylesheet\" id=\"skinlayercss\">\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "layer/layer.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\">\r\n");
	ViewBuilder.Append("    var Operation = {\r\n");
	ViewBuilder.Append("        save: function () {\r\n");
	ViewBuilder.Append("            formUtils.formSave();\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("    };\r\n");
	ViewBuilder.Append("    var QuickInput = function (content) {\r\n");
	ViewBuilder.Append("        content = $(\"#comment\").val() + content;\r\n");
	ViewBuilder.Append("        KindEditor.instances[0].html(content);\r\n");
	ViewBuilder.Append("        $(\"#comment\").val(content);\r\n");
	ViewBuilder.Append("    };\r\n");
	ViewBuilder.Append("    KindEditor.lang({\r\n");
	ViewBuilder.Append("        sign: '签名'\r\n");
	ViewBuilder.Append("    });\r\n");
	ViewBuilder.Append("    KindEditor.lang({\r\n");
	ViewBuilder.Append("        runi: '如拟'\r\n");
	ViewBuilder.Append("    });\r\n");
	ViewBuilder.Append("    KindEditor.lang({\r\n");
	ViewBuilder.Append("        tongyi: '同意'\r\n");
	ViewBuilder.Append("    });\r\n");
	ViewBuilder.Append("    KindEditor.lang({\r\n");
	ViewBuilder.Append("        yiyue: '已阅'\r\n");
	ViewBuilder.Append("    });\r\n");
	ViewBuilder.Append("    $(function () {\r\n");
	ViewBuilder.Append("        KindEditor.create('#comment', {\r\n");
	ViewBuilder.Append("            resizeType: 0,\r\n");
	ViewBuilder.Append("            filterMode: false,\r\n");
	ViewBuilder.Append("            minWidth: \"300px\",\r\n");
	ViewBuilder.Append("            minHeight: \"80px\",\r\n");
	ViewBuilder.Append("            items: [],\r\n");
	ViewBuilder.Append("            afterBlur: function () { this.sync(); }\r\n");
	ViewBuilder.Append("        });\r\n");
	ViewBuilder.Append("        KindEditor.create('.EDITOR-MINI', {\r\n");
	ViewBuilder.Append("            resizeType: 0,\r\n");
	ViewBuilder.Append("            filterMode: false,\r\n");
	ViewBuilder.Append("            minWidth: \"300px\",\r\n");
	ViewBuilder.Append("            minHeight: \"80px\",\r\n");
	ViewBuilder.Append("            items: ['sign', 'yiyue', 'tongyi', 'runi'],\r\n");
	ViewBuilder.Append("            afterBlur: function () { this.sync(); }\r\n");
	ViewBuilder.Append("        });\r\n");
	ViewBuilder.Append("        $(window).resize(function () {\r\n");
	ViewBuilder.Append("            var height = $(window).height();\r\n");
	ViewBuilder.Append("            $(\"#container-scroller\").height(height);\r\n");
	ViewBuilder.Append("            $(\"#container-scroller\").niceScroll({ cursorcolor: \"#ccc\", cursoropacitymin: 1, cursorwidth: 8 });\r\n");

	if (action=="comment")
	{
	ViewBuilder.Append("            $(\"#container-scroller\").getNiceScroll(0).doScrollTop(height, 1);\r\n");
	}//end if
	ViewBuilder.Append("        });\r\n");
	ViewBuilder.Append("        $(window).trigger(\"resize\");\r\n");
	ViewBuilder.Append("    });\r\n");
	ViewBuilder.Append("</");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<style type=\"text/css\">\r\n");
	ViewBuilder.Append("    a:link {\r\n");
	ViewBuilder.Append("	    color: #6d6d6d;\r\n");
	ViewBuilder.Append("	    text-decoration: none;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    img {\r\n");
	ViewBuilder.Append("	    border:0px\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    textarea {\r\n");
	ViewBuilder.Append("	    outline: none;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    a {\r\n");
	ViewBuilder.Append("	    color:#4f4f4f;\r\n");
	ViewBuilder.Append("	    text-decoration:none\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    ul, li {\r\n");
	ViewBuilder.Append("	    list-style:none;\r\n");
	ViewBuilder.Append("	    margin:0;\r\n");
	ViewBuilder.Append("	    padding:0;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .content-remark{\r\n");
	ViewBuilder.Append("        border: 1px solid #58C697;\r\n");
	ViewBuilder.Append("        width:800px;\r\n");
	ViewBuilder.Append("        margin:10px auto;\r\n");
	ViewBuilder.Append("        height: auto;\r\n");
	ViewBuilder.Append("        background-color: #fff;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .remark-block{\r\n");
	ViewBuilder.Append("        background: url(statics/images/remark-title.jpg) no-repeat left top;\r\n");
	ViewBuilder.Append("        position: relative;\r\n");
	ViewBuilder.Append("        text-align: left;\r\n");
	ViewBuilder.Append("        padding-left: 40px;\r\n");
	ViewBuilder.Append("        height: 60px;\r\n");
	ViewBuilder.Append("        font-size: 16px;\r\n");
	ViewBuilder.Append("        line-height: 60px;\r\n");
	ViewBuilder.Append("        font-weight: bold;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .remark-title {\r\n");
	ViewBuilder.Append("       padding-left: 0px;\r\n");
	ViewBuilder.Append("       color: #58C697;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list {\r\n");
	ViewBuilder.Append("        width:100%;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .msg_face, .comment_list .discussion_bubble_content {\r\n");
	ViewBuilder.Append("        float: left;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .comment_header {\r\n");
	ViewBuilder.Append("        height: 33px;\r\n");
	ViewBuilder.Append("        padding: 0 10px 0 6px;\r\n");
	ViewBuilder.Append("        border-bottom: 1px solid #ccc;\r\n");
	ViewBuilder.Append("        background-color: #e1e1e1;\r\n");
	ViewBuilder.Append("        background-image: -moz-linear-gradient(#f8f8f8, #e1e1e1);\r\n");
	ViewBuilder.Append("        background-image: -webkit-linear-gradient(#f8f8f8, #e1e1e1);\r\n");
	ViewBuilder.Append("        background-image: linear-gradient(#f8f8f8, #e1e1e1);\r\n");
	ViewBuilder.Append("        background-repeat: repeat-x;\r\n");
	ViewBuilder.Append("        font-size: 12px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content {\r\n");
	ViewBuilder.Append("        padding: 3px;\r\n");
	ViewBuilder.Append("        background: #eee;\r\n");
	ViewBuilder.Append("        border-radius: 3px;\r\n");
	ViewBuilder.Append("        width: 90%;\r\n");
	ViewBuilder.Append("        float: left;\r\n");
	ViewBuilder.Append("        margin-left: 18px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content .discussion_bubble_inner{\r\n");
	ViewBuilder.Append("        min-height: 32px;\r\n");
	ViewBuilder.Append("        border: 1px solid #CACACA;\r\n");
	ViewBuilder.Append("        background-color: #fff;position: relative;}\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content .discussion_bubble_inner .comment_header_task{\r\n");
	ViewBuilder.Append("        max-width: 600px;\r\n");
	ViewBuilder.Append("        float: left;\r\n");
	ViewBuilder.Append("        line-height: 33px;\r\n");
	ViewBuilder.Append("        font-weight: bold;\r\n");
	ViewBuilder.Append("        font-size: 14px;\r\n");
	ViewBuilder.Append("        color: #222;\r\n");
	ViewBuilder.Append("        text-shadow: 1px 1px 0 rgba(255,255,255,0.7);\r\n");
	ViewBuilder.Append("        overflow: hidden;\r\n");
	ViewBuilder.Append("        white-space: nowrap;\r\n");
	ViewBuilder.Append("        text-overflow: ellipsis;\r\n");
	ViewBuilder.Append("        margin-right: 5px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content .discussion_bubble_inner .comment_header_author{\r\n");
	ViewBuilder.Append("        max-width: 600px;\r\n");
	ViewBuilder.Append("        float: left;\r\n");
	ViewBuilder.Append("        line-height: 33px;\r\n");
	ViewBuilder.Append("        font-weight: bold;\r\n");
	ViewBuilder.Append("        color: #222;\r\n");
	ViewBuilder.Append("        text-shadow: 1px 1px 0 rgba(255,255,255,0.7);\r\n");
	ViewBuilder.Append("        overflow: hidden;\r\n");
	ViewBuilder.Append("        white-space: nowrap;\r\n");
	ViewBuilder.Append("        text-overflow: ellipsis;}\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content .discussion_bubble_inner .comment_header_date{\r\n");
	ViewBuilder.Append("        float:right;\r\n");
	ViewBuilder.Append("        display: inline-block;\r\n");
	ViewBuilder.Append("        margin: 0;\r\n");
	ViewBuilder.Append("        height: 33px;\r\n");
	ViewBuilder.Append("        font-size: 12px;\r\n");
	ViewBuilder.Append("        line-height: 33px;\r\n");
	ViewBuilder.Append("        font-style: normal;\r\n");
	ViewBuilder.Append("        color: #777;\r\n");
	ViewBuilder.Append("        text-shadow: 1px 1px 0 rgba(255,255,255,0.7);\r\n");
	ViewBuilder.Append("        line-height: 33px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content .discussion_bubble_inner .comment_content{\r\n");
	ViewBuilder.Append("        padding: 3px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .arrow {\r\n");
	ViewBuilder.Append("        top:20px;\r\n");
	ViewBuilder.Append("        position: absolute;\r\n");
	ViewBuilder.Append("        margin: 0 0 0;\r\n");
	ViewBuilder.Append("        margin: -1px 0 0/9;\r\n");
	ViewBuilder.Append("        width: 19px;\r\n");
	ViewBuilder.Append("        cursor: default;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .arrow * {\r\n");
	ViewBuilder.Append("        font-family: \"SimSun\";\r\n");
	ViewBuilder.Append("        overflow: hidden;\r\n");
	ViewBuilder.Append("        font-size: 30px;\r\n");
	ViewBuilder.Append("        line-height:40px;\r\n");
	ViewBuilder.Append("        display: block;\r\n");
	ViewBuilder.Append("        height: 40px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .arrow em{\r\n");
	ViewBuilder.Append("        color: #eee;\r\n");
	ViewBuilder.Append("        font-style: normal;\r\n");
	ViewBuilder.Append("        font-weight: normal;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .arrow span {\r\n");
	ViewBuilder.Append("        color: #eee;\r\n");
	ViewBuilder.Append("        margin: -12px 0 0 -1px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_box .arrow {\r\n");
	ViewBuilder.Append("        left: -20px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_box .arrow span{\r\n");
	ViewBuilder.Append("        margin-left:1px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("     /* lch 2017-7-7 */\r\n");
	ViewBuilder.Append("    .th {\r\n");
	ViewBuilder.Append("        background-color:#edf2f3;\r\n");
	ViewBuilder.Append("        /*#d6e1e4  rgb(239, 240, 245)*/\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    input {\r\n");
	ViewBuilder.Append("	height: 30px;\r\n");
	ViewBuilder.Append("	border: 0;\r\n");
	ViewBuilder.Append("	border: 1px #ccc solid;\r\n");
	ViewBuilder.Append("	padding-left: 5px;\r\n");
	ViewBuilder.Append("	padding-right: 5px;\r\n");
	ViewBuilder.Append("	border-radius: 4px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    input:focus {\r\n");
	ViewBuilder.Append("	    height: 30px;\r\n");
	ViewBuilder.Append("	    border: 1px #8ab7ed solid;\r\n");
	ViewBuilder.Append("	    border-radius: 4px;\r\n");
	ViewBuilder.Append("	    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(82, 168, 236, 0.6);\r\n");
	ViewBuilder.Append("	    -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(82, 168, 236, 0.6);\r\n");
	ViewBuilder.Append("	    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(82, 168, 236, 0.6);\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .ke-icon-sign\r\n");
	ViewBuilder.Append("    {\r\n");
	ViewBuilder.Append("        background-image: url(" + echo(plupath) + "kindeditor/themes/default/icon_sign.png);\r\n");
	ViewBuilder.Append("        width: 32px;\r\n");
	ViewBuilder.Append("        height: 20px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .ke-icon-runi\r\n");
	ViewBuilder.Append("    {\r\n");
	ViewBuilder.Append("        background-image: url(" + echo(plupath) + "kindeditor/themes/default/icon_runi.png);\r\n");
	ViewBuilder.Append("        width: 32px;\r\n");
	ViewBuilder.Append("        height: 20px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .ke-icon-tongyi\r\n");
	ViewBuilder.Append("    {\r\n");
	ViewBuilder.Append("        background-image: url(" + echo(plupath) + "kindeditor/themes/default/icon_tongyi.png);\r\n");
	ViewBuilder.Append("        width: 32px;\r\n");
	ViewBuilder.Append("        height: 20px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .ke-icon-yiyue\r\n");
	ViewBuilder.Append("    {\r\n");
	ViewBuilder.Append("        background-image: url(" + echo(plupath) + "kindeditor/themes/default/icon_yiyue.png);\r\n");
	ViewBuilder.Append("        width: 32px;\r\n");
	ViewBuilder.Append("        height: 20px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("</style>\r\n");
	ViewBuilder.Append("</head>\r\n");
	ViewBuilder.Append("<body style=\"overflow: hidden; \">\r\n");
	ViewBuilder.Append("    <div id=\"container-scroller\">\r\n");
	ViewBuilder.Append("        <form enctype=\"multipart/form-data\" id=\"frmpost\" name=\"frmpost\" action=\"\" method=\"post\">\r\n");
	ViewBuilder.Append("        <input id=\"txtUser\" type=\"hidden\" value=\"" + echo(realname) + "\">\r\n");
	ViewBuilder.Append("        <input id=\"txtDate\" type=\"hidden\" value='" + echo(datetime,"yyyy年MM月dd日") + "'>\r\n");
	ViewBuilder.Append("        <div class=\"divTable\">\r\n");
	ViewBuilder.Append("            <input id=\"action\" name=\"action\" value=\"form\" type=\"hidden\">\r\n");
	ViewBuilder.Append("            <input id=\"id\" name=\"id\" value=\"" + echo(id) + "\" type=\"hidden\">\r\n");
	ViewBuilder.Append("            " + echo(forminfo.content) + "\r\n");
	ViewBuilder.Append("        </div>\r\n");
	ViewBuilder.Append("        </form>\r\n");

	if (workflowinfo.isback==-1)
	{
	ViewBuilder.Append("        <div style=\"width:800px;margin:0px auto;\">\r\n");
	ViewBuilder.Append("            <span style=\"font-weight:bold;color:#db3600\">回退原因：" + echo(workflowinfo.content) + "</span>\r\n");
	ViewBuilder.Append("        </div>\r\n");
	}//end if
	ViewBuilder.Append("    </div>\r\n");
	ViewBuilder.Append("    <iframe id=\"download_attach\" name=\"download_attach\" width=\"0\" height=\"0\"></iframe>\r\n");
	ViewBuilder.Append("    <script type=\"text/javascript\">\r\n");
	ViewBuilder.Append("        $(function () {\r\n");
	ViewBuilder.Append("            $('#file_upload').uploadify({\r\n");
	ViewBuilder.Append("                'swf': '" + echo(plupath) + "uploadify/uploadify.swf',\r\n");
	ViewBuilder.Append("                'uploader': '" + echo(plupath) + "attach/upload.aspx',\r\n");
	ViewBuilder.Append("                \"formData\": {'token':'" + echo(token) + "','attachid': '" + echo(workflowinfo.attachid) + "', 'app': '" + echo(setupinfo.markup) + "', 'postid': '" + echo(workflowinfo.id) + "'},\r\n");
	ViewBuilder.Append("                'fileTypeExts': '" + echo(AttachBll.GetAttachTypeExts()) + "',\r\n");
	ViewBuilder.Append("                'onUploadSuccess': function (file, data) {\r\n");
	ViewBuilder.Append("                    var obj = (new Function(\"return \" + data))();\r\n");
	ViewBuilder.Append("                    if (obj.errcode ==0) {\r\n");
	ViewBuilder.Append("                        var html = \"<div class=\\\"attachment-wrapper\\\" id=\\\"attachment_\" + obj.aid + \"\\\">\";\r\n");
	ViewBuilder.Append("                        html += \"<div class=\\\"dropdown clearfix\\\">\";\r\n");
	ViewBuilder.Append("                        html += \"<a href=\\\"javascript:;\\\" class=\\\"dropdown-toggle\\\" onclick=\\\"TUtil.openUrl('" + echo(plupath) + "pdf/index.aspx?aid=\" + obj.aid + \"');\\\"><img src=\\\"\" + obj.icon + \"\\\" />\" + obj.name + \"</a>\";\r\n");
	ViewBuilder.Append("                        html += \"<ul class=\\\"dropdown-menu\\\">\";\r\n");
	ViewBuilder.Append("                        html += \"<li><a href=\\\"" + echo(plupath) + "attach/download.aspx?aid=\" + obj.aid + \"\\\" target=\\\"download_attach\\\">下载</a></li>\";\r\n");
	ViewBuilder.Append("                        html += \"<li><a href=\\\"javascript:;\\\" onclick=\\\"TUtil.openUrl('" + echo(plupath) + "pdf/index.aspx?aid=\" + obj.aid + \"');\\\">阅读</a></li>\";\r\n");
	ViewBuilder.Append("                        html += \"<li><a href=\\\"javascript:;\\\" onclick=\\\"TUtil.openUrl('" + echo(plupath) + "ntko/index.aspx?aid=\" + obj.aid + \"');\\\">编辑</a></li>\";\r\n");
	ViewBuilder.Append("                        html += \"<li><a href=\\\"javascript:;\\\" onclick=\\\"javascript:Attachment.deleteAttach('" + echo(plupath) + "attach/delete.aspx?aid=\" + obj.aid + \"');return false;\\\">删除</a></li>\";\r\n");
	ViewBuilder.Append("                        html += \"<li><a href=\\\"" + echo(plupath) + "attach/download.aspx?attachid=" + echo(workflowinfo.attachid) + "&filename=" + FPUtils.RemoveHtml(workflowinfo.title) + "_批量附件下载\\\" target=\\\"download_attach\\\">批量下载</a></li>\";\r\n");
	ViewBuilder.Append("                        html += \"</ul>\";\r\n");
	ViewBuilder.Append("                        html += \"</div>\";\r\n");
	ViewBuilder.Append("                        html += \"</div>\";\r\n");
	ViewBuilder.Append("                        $(\"#file-container\").append(html);\r\n");
	ViewBuilder.Append("                    }\r\n");
	ViewBuilder.Append("                    else {\r\n");
	ViewBuilder.Append("                        alert(obj.errmsg);\r\n");
	ViewBuilder.Append("                    }\r\n");
	ViewBuilder.Append("                }\r\n");
	ViewBuilder.Append("            });\r\n");
	ViewBuilder.Append("            $(\"#submitComment\").live(\"click\", function () {\r\n");
	ViewBuilder.Append("                $(\"#frmcomment\").submit();\r\n");
	ViewBuilder.Append("            });\r\n");
	ViewBuilder.Append("            $(\"#btn_end\").live(\"click\", function () {\r\n");
	ViewBuilder.Append("                if (parent.Operation !== undefined) {\r\n");
	ViewBuilder.Append("                    parent.Operation.turnend();\r\n");
	ViewBuilder.Append("                }\r\n");
	ViewBuilder.Append("            });\r\n");
	ViewBuilder.Append("            $(\"#btn_quick\").live(\"click\", function () {\r\n");
	ViewBuilder.Append("                $.layer({\r\n");
	ViewBuilder.Append("                    type: 2,\r\n");
	ViewBuilder.Append("                    shade: [0],\r\n");
	ViewBuilder.Append("                    fix: false,\r\n");
	ViewBuilder.Append("                    title: '会签快捷输入',\r\n");
	ViewBuilder.Append("                    maxmin: false,\r\n");
	ViewBuilder.Append("                    iframe: { src: 'signlist.aspx' },\r\n");
	ViewBuilder.Append("                    area: [500, 450]\r\n");
	ViewBuilder.Append("                });\r\n");
	ViewBuilder.Append("            });\r\n");
	ViewBuilder.Append("        })\r\n");
	ViewBuilder.Append("    </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("</body>\r\n");
	ViewBuilder.Append("</html>\r\n");
	if(iswrite==0)
	{
	Response.Write(ViewBuilder.ToString());
	}
	else if(iswrite==1)
	{
	Hashtable hash = new Hashtable();
	hash["errcode"] = 0;
	hash["errmsg"] ="";
	hash["html"]=ViewBuilder.ToString();
	FPResponse.WriteJson(hash);
	}
}
</script>
