<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="FP_WorkFlow.Controller.flowform" %>
<%@ Import namespace="System.Collections.Generic" %>
<%@ Import namespace="FangPage.Common" %>
<%@ Import namespace="FangPage.MVC" %>
<%@ Import namespace="FP_WorkFlow" %>
<%@ Import namespace="FP_WorkFlow.Model" %>
<%@ Import namespace="FangPage.WMS.Model" %>
<%@ Import namespace="FangPage.WMS.Bll" %>
<script runat="server">
protected override void View()
{
	base.View();
	ViewBuilder.Append("<!DOCTYPE html>\r\n");
	ViewBuilder.Append("<html>\r\n");
	ViewBuilder.Append("<head>\r\n");
	ViewBuilder.Append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
	ViewBuilder.Append("<title>表单处理</title>\r\n");
	ViewBuilder.Append("	" + echo(meta) + "\r\n");
	ViewBuilder.Append("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
	ViewBuilder.Append("<meta name=\"renderer\" content=\"webkit\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/bootstrap.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/bootstrap-notify.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/bootstrap-modal.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/bootstrap-file-selector.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/icomoon.css\">\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "jquery/jquery.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "nicescroll/jquery.nicescroll.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap.bootbox.min.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap.notify.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap-prompts.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap.min.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap-modal.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap-modalmanager.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "multifile/jquery.multifile.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "jform/jquery.form.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "modernizr/modernizr-2.6.1.min.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"/oa/public/js/util.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"/oa/public/js/form.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"/oa/public/js/attachment.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "uploadify/jquery.uploadify.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "uploadify/uploadify.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"/oa/public/css/fp-bootstrap.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "editor/themes/default/default.css\">\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "editor/kindeditor.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "editor/lang/zh_CN.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" href=\"" + echo(plupath) + "layer/skin/layer.css\" type=\"text/css\" id=\"skinlayercss\">\r\n");
	ViewBuilder.Append("<script src=\"" + echo(plupath) + "layer/layer.js\" type=\"text/javascript\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\">\r\n");
	ViewBuilder.Append("    var Operation = {\r\n");
	ViewBuilder.Append("        save: function () {\r\n");
	ViewBuilder.Append("            formUtils.formSave();\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("    };\r\n");
	ViewBuilder.Append("    var QuickInput = function (content) {\r\n");
	ViewBuilder.Append("        KindEditor.instances[0].html(content);\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    $(function () {\r\n");
	ViewBuilder.Append("        $(window).resize(function () {\r\n");
	ViewBuilder.Append("            var height = $(window).height();\r\n");
	ViewBuilder.Append("            $(\"#container-scroller\").height(height);\r\n");
	ViewBuilder.Append("            $(\"#container-scroller\").niceScroll({ cursorcolor: \"#ccc\" ,cursoropacitymin:1,cursorwidth:8});\r\n");
	ViewBuilder.Append("        });\r\n");
	ViewBuilder.Append("        $(window).trigger(\"resize\");\r\n");
	ViewBuilder.Append("        KindEditor.create('#comment', {\r\n");
	ViewBuilder.Append("            resizeType: 1,\r\n");
	ViewBuilder.Append("            uploadJson: '" + echo(plupath) + "editor/uploadajax.aspx?sortid=0',\r\n");
	ViewBuilder.Append("            fileManagerJson: '" + echo(plupath) + "editor/filemanagerajax.aspx',\r\n");
	ViewBuilder.Append("            newlineTag: \"br\",\r\n");
	ViewBuilder.Append("            items: ['fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline',\r\n");
	ViewBuilder.Append("					'removeformat', '|', 'image', 'flash', 'media', '|', 'link', 'unlink'],\r\n");
	ViewBuilder.Append("            afterBlur: function () { this.sync(); }\r\n");
	ViewBuilder.Append("        });\r\n");
	ViewBuilder.Append("    });\r\n");
	ViewBuilder.Append("</");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<style type=\"text/css\">\r\n");
	ViewBuilder.Append("    a:link {\r\n");
	ViewBuilder.Append("	color: #6d6d6d;\r\n");
	ViewBuilder.Append("	text-decoration: none;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    img {\r\n");
	ViewBuilder.Append("	    border:0px\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    input {\r\n");
	ViewBuilder.Append("	    outline: none;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    textarea {\r\n");
	ViewBuilder.Append("	    outline: none;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    a {\r\n");
	ViewBuilder.Append("	    color:#4f4f4f;\r\n");
	ViewBuilder.Append("	    text-decoration:none\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    ul, li {\r\n");
	ViewBuilder.Append("	    list-style:none;\r\n");
	ViewBuilder.Append("	    margin:0;\r\n");
	ViewBuilder.Append("	    padding:0;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .content-remark{\r\n");
	ViewBuilder.Append("        border: 1px solid #58C697;\r\n");
	ViewBuilder.Append("        width:900px;\r\n");
	ViewBuilder.Append("        margin:10px auto;\r\n");
	ViewBuilder.Append("        height: auto;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .remark-block{\r\n");
	ViewBuilder.Append("        background: url(statics/images/remark-title.jpg) no-repeat left top;\r\n");
	ViewBuilder.Append("        position: relative;\r\n");
	ViewBuilder.Append("        text-align: left;\r\n");
	ViewBuilder.Append("        padding-left: 40px;\r\n");
	ViewBuilder.Append("        height: 60px;\r\n");
	ViewBuilder.Append("        font-size: 16px;\r\n");
	ViewBuilder.Append("        line-height: 60px;\r\n");
	ViewBuilder.Append("        font-weight: bold;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .remark-title {\r\n");
	ViewBuilder.Append("       padding-left: 0px;\r\n");
	ViewBuilder.Append("       color: #58C697;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list {\r\n");
	ViewBuilder.Append("        width:100%;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .msg_face, .comment_list .discussion_bubble_content {\r\n");
	ViewBuilder.Append("        float: left;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .comment_header {\r\n");
	ViewBuilder.Append("        height: 33px;\r\n");
	ViewBuilder.Append("        padding: 0 10px 0 6px;\r\n");
	ViewBuilder.Append("        border-bottom: 1px solid #ccc;\r\n");
	ViewBuilder.Append("        background-color: #e1e1e1;\r\n");
	ViewBuilder.Append("        background-image: -moz-linear-gradient(#f8f8f8, #e1e1e1);\r\n");
	ViewBuilder.Append("        background-image: -webkit-linear-gradient(#f8f8f8, #e1e1e1);\r\n");
	ViewBuilder.Append("        background-image: linear-gradient(#f8f8f8, #e1e1e1);\r\n");
	ViewBuilder.Append("        background-repeat: repeat-x;\r\n");
	ViewBuilder.Append("        font-size: 12px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content {\r\n");
	ViewBuilder.Append("        padding: 3px;\r\n");
	ViewBuilder.Append("        background: #eee;\r\n");
	ViewBuilder.Append("        border-radius: 3px;\r\n");
	ViewBuilder.Append("        width: 90%;\r\n");
	ViewBuilder.Append("        float: left;\r\n");
	ViewBuilder.Append("        margin-left: 18px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content .discussion_bubble_inner{\r\n");
	ViewBuilder.Append("        min-height: 32px;\r\n");
	ViewBuilder.Append("        border: 1px solid #CACACA;\r\n");
	ViewBuilder.Append("        background-color: #fff;position: relative;}\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content .discussion_bubble_inner .comment_header_task{\r\n");
	ViewBuilder.Append("        max-width: 600px;\r\n");
	ViewBuilder.Append("        float: left;\r\n");
	ViewBuilder.Append("        line-height: 33px;\r\n");
	ViewBuilder.Append("        font-weight: bold;\r\n");
	ViewBuilder.Append("        font-size: 14px;\r\n");
	ViewBuilder.Append("        color: #222;\r\n");
	ViewBuilder.Append("        text-shadow: 1px 1px 0 rgba(255,255,255,0.7);\r\n");
	ViewBuilder.Append("        overflow: hidden;\r\n");
	ViewBuilder.Append("        white-space: nowrap;\r\n");
	ViewBuilder.Append("        text-overflow: ellipsis;\r\n");
	ViewBuilder.Append("        margin-right: 5px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content .discussion_bubble_inner .comment_header_author{\r\n");
	ViewBuilder.Append("        max-width: 600px;\r\n");
	ViewBuilder.Append("        float: left;\r\n");
	ViewBuilder.Append("        line-height: 33px;\r\n");
	ViewBuilder.Append("        font-weight: bold;\r\n");
	ViewBuilder.Append("        color: #222;\r\n");
	ViewBuilder.Append("        text-shadow: 1px 1px 0 rgba(255,255,255,0.7);\r\n");
	ViewBuilder.Append("        overflow: hidden;\r\n");
	ViewBuilder.Append("        white-space: nowrap;\r\n");
	ViewBuilder.Append("        text-overflow: ellipsis;}\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content .discussion_bubble_inner .comment_header_date{\r\n");
	ViewBuilder.Append("        float:right;\r\n");
	ViewBuilder.Append("        display: inline-block;\r\n");
	ViewBuilder.Append("        margin: 0;\r\n");
	ViewBuilder.Append("        height: 33px;\r\n");
	ViewBuilder.Append("        font-size: 11px;\r\n");
	ViewBuilder.Append("        line-height: 33px;\r\n");
	ViewBuilder.Append("        font-style: normal;\r\n");
	ViewBuilder.Append("        color: #777;\r\n");
	ViewBuilder.Append("        text-shadow: 1px 1px 0 rgba(255,255,255,0.7);\r\n");
	ViewBuilder.Append("        line-height: 33px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_list .discussion_bubble_content .discussion_bubble_inner .comment_content{\r\n");
	ViewBuilder.Append("        padding: 10px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .arrow {\r\n");
	ViewBuilder.Append("        top:20px;\r\n");
	ViewBuilder.Append("        position: absolute;\r\n");
	ViewBuilder.Append("        margin: 0 0 0;\r\n");
	ViewBuilder.Append("        margin: -1px 0 0/9;\r\n");
	ViewBuilder.Append("        width: 19px;\r\n");
	ViewBuilder.Append("        cursor: default;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .arrow * {\r\n");
	ViewBuilder.Append("        font-family: \"SimSun\";\r\n");
	ViewBuilder.Append("        overflow: hidden;\r\n");
	ViewBuilder.Append("        font-size: 30px;\r\n");
	ViewBuilder.Append("        line-height:40px;\r\n");
	ViewBuilder.Append("        display: block;\r\n");
	ViewBuilder.Append("        height: 40px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .arrow em{\r\n");
	ViewBuilder.Append("        color: #eee;\r\n");
	ViewBuilder.Append("        font-style: normal;\r\n");
	ViewBuilder.Append("        font-weight: normal;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .arrow span {\r\n");
	ViewBuilder.Append("        color: #eee;\r\n");
	ViewBuilder.Append("        margin: -12px 0 0 -1px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_box .arrow {\r\n");
	ViewBuilder.Append("        left: -20px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    .comment_box .arrow span{\r\n");
	ViewBuilder.Append("        margin-left:1px;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("     /* lch 2017-7-7 */\r\n");
	ViewBuilder.Append("    .th {\r\n");
	ViewBuilder.Append("        background-color:#edf2f3;\r\n");
	ViewBuilder.Append("        /*#d6e1e4  rgb(239, 240, 245)*/\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    input {\r\n");
	ViewBuilder.Append("        border:1px solid #a7a1a1 !important;\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("</style>\r\n");
	ViewBuilder.Append("</head>\r\n");
	ViewBuilder.Append("<body style=\"overflow: hidden; \">\r\n");
	ViewBuilder.Append("    <div id=\"container-scroller\">\r\n");
	ViewBuilder.Append("        <form enctype=\"multipart/form-data\" id=\"frmpost\" name=\"frmpost\" action=\"\" method=\"post\">\r\n");
	ViewBuilder.Append("        <div class=\"divTable\">\r\n");
	ViewBuilder.Append("            <input id=\"action\" name=\"action\" value=\"form\" type=\"hidden\">\r\n");
	ViewBuilder.Append("            <input id=\"id\" name=\"id\" value=\"" + echo(id) + "\" type=\"hidden\">\r\n");
	ViewBuilder.Append("            " + echo(forminfo.content) + "\r\n");
	ViewBuilder.Append("        </div>\r\n");
	ViewBuilder.Append("        </form>\r\n");
	ViewBuilder.Append("        <div class=\"content-remark\">\r\n");
	ViewBuilder.Append("            <div class=\"remark-block\">\r\n");
	ViewBuilder.Append("                <span class=\"remark-title\">会签意见区</span>\r\n");
	ViewBuilder.Append("            </div>\r\n");
	ViewBuilder.Append("            <div>\r\n");

	loop__id=0;
	foreach(CommentInfo item in commentlist)
	{
	loop__id++;
	ViewBuilder.Append("                <div class=\"comment_list\">\r\n");
	ViewBuilder.Append("                  <dl class=\"T_linecolor  comment_box clearfix\" style=\"margin:10px 0\">\r\n");
	ViewBuilder.Append("                    <dt class=\"msg_face\"><img src=\"/" + echo(item.avatar) + "\" width=\"50\" height=\"50\"> </dt>\r\n");
	ViewBuilder.Append("                    <dd class=\"discussion_bubble_content\">\r\n");
	ViewBuilder.Append("                      <div class=\"discussion_bubble_inner\">\r\n");
	ViewBuilder.Append("                        <div class=\"R_msg\">\r\n");
	ViewBuilder.Append("                          <div class=\"private_operate clearfix\">\r\n");
	ViewBuilder.Append("                            <div class=\"comment_header\">\r\n");
	ViewBuilder.Append("                              <div class=\"comment_header_task\">第" + echo(item.step) + "步：" + echo(item.stepname) + "</div>\r\n");
	ViewBuilder.Append("                              <div class=\"comment_header_author\" title=\"部门：" + echo(item.departname) + "\">" + echo(item.realname) + "/" + echo(item.title) + "</div>\r\n");
	ViewBuilder.Append("                              <div class=\"comment_header_date\" style=\"float:right;\">" + echo(item.postdatetime,"yyyy-MM-dd HH:mm:ss") + "</div>\r\n");
	ViewBuilder.Append("                            </div>\r\n");
	List<AttachInfo> attachlist = AttachBll.GetAttachList(item.attachid);
	ViewBuilder.Append("                            <div class=\"comment_content\">" + echo(item.content) + "\r\n");

	if (attachlist.Count>0)
	{
	ViewBuilder.Append("                                   <br>附件：\r\n");

	loop__id=0;
	foreach(AttachInfo attr in attachlist)
	{
	loop__id++;
	ViewBuilder.Append("                                   <div class=\"attachment-wrapper\" id=\"attachment_" + echo(attr.id) + "\">\r\n");
	ViewBuilder.Append("                                       <div class=\"dropdown clearfix\">\r\n");
	ViewBuilder.Append("                                       <a class=\"dropdown-toggle\" href=\"" + echo(plupath) + "pdf/index.aspx?aid=" + echo(attr.id) + "\"><img src=\"" + echo(webpath) + "common/file/" + echo(FormatExt(attr.filename)) + ".gif\">" + echo(attr.name) + "</a>\r\n");
	ViewBuilder.Append("                                       <ul class=\"dropdown-menu\">\r\n");
	ViewBuilder.Append("                                           <li><a href=\"" + echo(plupath) + "attach/download.aspx?aid=" + echo(attr.id) + "\">下载</a></li>\r\n");
	ViewBuilder.Append("                                           <li><a target=\"_blank\" href=\"" + echo(plupath) + "pdf/index.aspx?aid=" + echo(attr.id) + "\">阅读</a></li>\r\n");
	ViewBuilder.Append("                                       </ul>\r\n");
	ViewBuilder.Append("                                       </div>\r\n");
	ViewBuilder.Append("                                   </div>\r\n");
	}//end loop
	}//end if
	ViewBuilder.Append("                            </div>\r\n");
	ViewBuilder.Append("                          </div>\r\n");
	ViewBuilder.Append("                        </div>\r\n");
	ViewBuilder.Append("                        <div class=\"arrow\"><span>◆</span></div>\r\n");
	ViewBuilder.Append("                      </div>\r\n");
	ViewBuilder.Append("                    </dd>\r\n");
	ViewBuilder.Append("                  </dl>\r\n");
	ViewBuilder.Append("                </div>\r\n");
	}//end loop

	if (workflowinfo.status<=2)
	{
	ViewBuilder.Append("            <div class=\"comment_list\">\r\n");
	ViewBuilder.Append("              <dl class=\"T_linecolor  comment_box clearfix\">\r\n");
	ViewBuilder.Append("                <dt class=\"msg_face\"><img src=\"/" + echo(workflowinfo.receive_avatar) + "\" width=\"50\" height=\"50\"> </dt>\r\n");
	ViewBuilder.Append("                <dd class=\"discussion_bubble_content\">\r\n");
	ViewBuilder.Append("                  <div class=\"discussion_bubble_inner\">\r\n");
	ViewBuilder.Append("                    <div class=\"comment_content\">\r\n");
	ViewBuilder.Append("                      <form style=\"margin:0px;\" id=\"frmcomment\" name=\"frmcomment\" action=\"\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
	ViewBuilder.Append("                        <input type=\"hidden\" id=\"action_comment\" name=\"action\" value=\"comment\">\r\n");
	ViewBuilder.Append("                        <label for=\"comment\" class=\"required\">第" + echo(workflowinfo.step) + "步：" + echo(workflowinfo.stepname) + "&nbsp;&nbsp;我的意见/" + echo(workflowinfo.isadmin_show) + "</label>\r\n");
	ViewBuilder.Append("                        <textarea id=\"comment\" name=\"comment\" style=\"width:800px; height:150px\">" + echo(commentinfo.content) + "</textarea>\r\n");
	ViewBuilder.Append("                        <label class=\"required\">\r\n");
	ViewBuilder.Append("                            <div>\r\n");
	ViewBuilder.Append("                               <a class=\"btn btn-link file-selector\">\r\n");
	ViewBuilder.Append("                                    <i class=\"icon-file-upload\"></i>上传附件\r\n");
	ViewBuilder.Append("                                    <div class=\"MultiFile-wrap\">\r\n");
	ViewBuilder.Append("                                    <input name=\"addfile\" id=\"addfile\" type=\"file\" class=\"multi-pt\" value=\"\">\r\n");
	ViewBuilder.Append("                                    </div>\r\n");
	ViewBuilder.Append("                                </a>\r\n");
	ViewBuilder.Append("                                <div id=\"file-container2\"></div>\r\n");

	loop__id=0;
	foreach(AttachInfo attr in AttachBll.GetAttachList(commentinfo.attachid))
	{
	loop__id++;
	ViewBuilder.Append("                                   <div class=\"attachment-wrapper\" id=\"attachment_" + echo(attr.id) + "\">\r\n");
	ViewBuilder.Append("                                       <div class=\"dropdown clearfix\">\r\n");
	ViewBuilder.Append("                                       <a class=\"dropdown-toggle\" href=\"" + echo(plupath) + "pdf/index.aspx?aid=" + echo(attr.id) + "\"><img src=\"" + echo(webpath) + "common/file/" + echo(FormatExt(attr.filename)) + ".gif\">" + echo(attr.name) + "</a>\r\n");
	ViewBuilder.Append("                                       <ul class=\"dropdown-menu\">\r\n");
	ViewBuilder.Append("                                           <li><a href=\"" + echo(plupath) + "attach/download.aspx?aid=" + echo(attr.id) + "\">下载</a></li>\r\n");
	ViewBuilder.Append("                                           <li><a target=\"_blank\" href=\"" + echo(plupath) + "pdf/index.aspx?aid=" + echo(attr.id) + "\">阅读</a></li>\r\n");
	ViewBuilder.Append("                                       </ul>\r\n");
	ViewBuilder.Append("                                       </div>\r\n");
	ViewBuilder.Append("                                   </div>\r\n");
	}//end loop
	ViewBuilder.Append("                            </div>\r\n");
	ViewBuilder.Append("                        </label>\r\n");
	ViewBuilder.Append("                      </form>\r\n");
	ViewBuilder.Append("                      <button id=\"btn_quick\" class=\"btn btn-danger\" name=\"btn_quick\" type=\"button\">快捷输入</button>\r\n");
	ViewBuilder.Append("                      <button id=\"submitComment\" class=\"btn btn-danger\" name=\"submitComment\" type=\"button\">发表</button>\r\n");
	ViewBuilder.Append("                    </div>\r\n");
	ViewBuilder.Append("                    <div class=\"arrow\"><span>◆</span></div>\r\n");
	ViewBuilder.Append("                  </div>\r\n");
	ViewBuilder.Append("                </dd>\r\n");
	ViewBuilder.Append("              </dl>\r\n");
	ViewBuilder.Append("            </div>\r\n");
	}//end if
	ViewBuilder.Append("            </div>\r\n");
	ViewBuilder.Append("        </div>\r\n");
	ViewBuilder.Append("    </div>\r\n");
	ViewBuilder.Append("    <script type=\"text/javascript\">\r\n");
	ViewBuilder.Append("        $(function () {\r\n");
	ViewBuilder.Append("            $('#file_upload').uploadify({\r\n");
	ViewBuilder.Append("                'swf': '" + echo(plupath) + "uploadify/uploadify.swf',\r\n");
	ViewBuilder.Append("                'uploader': '" + echo(plupath) + "attach/upload.aspx',\r\n");
	ViewBuilder.Append("                \"formData\": { 'attachid': '" + echo(workflowinfo.attachid) + "', 'status': '1', 'app': '" + echo(setupinfo.markup) + "', 'postid': '" + echo(workflowinfo.id) + "' },\r\n");
	ViewBuilder.Append("                'fileTypeExts': '" + echo(AttachBll.GetAttachTypeExts()) + "',\r\n");
	ViewBuilder.Append("                'onUploadSuccess': function (file, data, response) {\r\n");
	ViewBuilder.Append("                    var obj = (new Function(\"return \" + data))();\r\n");
	ViewBuilder.Append("                    if (obj.msg == '') {\r\n");
	ViewBuilder.Append("                        var html = \"<div class=\\\"attachment-wrapper\\\" id=\\\"attachment_\" + obj.aid + \"\\\">\";\r\n");
	ViewBuilder.Append("                        html += \"<div class=\\\"dropdown clearfix\\\">\";\r\n");
	ViewBuilder.Append("                        html += \"<a class=\\\"dropdown-toggle\\\" href=\\\"" + echo(plupath) + "pdf/index.aspx?aid=\" + obj.aid + \"\\\"><img src=\\\"" + echo(webpath) + "common/file/\" + obj.filetype + \".gif\\\" />\" + obj.name + \"</a><span class=\\\"size\\\">(\" + obj.size + \")</span>\";\r\n");
	ViewBuilder.Append("                        html += \"<ul class=\\\"dropdown-menu\\\">\";\r\n");
	ViewBuilder.Append("                        html += \"<li><a href=\\\"" + echo(plupath) + "attach/download.aspx?aid=\" + obj.aid + \"\\\">下载</a></li>\";\r\n");
	ViewBuilder.Append("                        html += \"<li><a target=\\\"_blank\\\" href=\\\"" + echo(plupath) + "pdf/index.aspx?aid=\" + obj.aid + \"\\\">阅读</a></li>\";\r\n");
	ViewBuilder.Append("                        html += \"<li><a target=\\\"_blank\\\" href=\\\"" + echo(plupath) + "ntko/index.aspx?aid=\" + obj.aid + \"\\\">编辑</a></li>\";\r\n");
	ViewBuilder.Append("                        html += \"<li><a onclick=\\\"javascript:Attachment.deleteAttach('" + echo(plupath) + "attach/delete.aspx?aid=\" + obj.aid + \"');return false;\\\" href=\\\"#\\\">删除</a></li>\";\r\n");
	ViewBuilder.Append("                        html += \"</div>\";\r\n");
	ViewBuilder.Append("                        html += \"</div>\";\r\n");
	ViewBuilder.Append("                        $(\"#file-container\").append(html);\r\n");
	ViewBuilder.Append("                    }\r\n");
	ViewBuilder.Append("                    else {\r\n");
	ViewBuilder.Append("                        alert(obj.msg);\r\n");
	ViewBuilder.Append("                    }\r\n");
	ViewBuilder.Append("                }\r\n");
	ViewBuilder.Append("            });\r\n");
	ViewBuilder.Append("            $(\"#submitComment\").live(\"click\", function () {\r\n");
	ViewBuilder.Append("                $(\"#frmcomment\").submit();\r\n");
	ViewBuilder.Append("            });\r\n");
	ViewBuilder.Append("            $(\"#btn_quick\").live(\"click\", function () {\r\n");
	ViewBuilder.Append("                $.layer({\r\n");
	ViewBuilder.Append("                    type: 2,\r\n");
	ViewBuilder.Append("                    shade: [0],\r\n");
	ViewBuilder.Append("                    fix: false,\r\n");
	ViewBuilder.Append("                    title: '会签快捷输入',\r\n");
	ViewBuilder.Append("                    maxmin: false,\r\n");
	ViewBuilder.Append("                    iframe: { src: 'signlist.aspx' },\r\n");
	ViewBuilder.Append("                    area: [500, 450]\r\n");
	ViewBuilder.Append("                });\r\n");
	ViewBuilder.Append("            });\r\n");
	ViewBuilder.Append("            $('#addfile').MultiFile({\r\n");
	ViewBuilder.Append("                'accept': '" + echo(AttachBll.GetAttachTypeString()) + "',\r\n");
	ViewBuilder.Append("                'list': '#file-container2',\r\n");
	ViewBuilder.Append("                'STRING': {\r\n");
	ViewBuilder.Append("                    'remove': '<i class=\\\"icon-file-remove-2\\\" rel=\\\"tooltip\\\" title=\\\"移除文件\\\"><\\/i>',\r\n");
	ViewBuilder.Append("                    'selected': '文件：$file', 'denied': '禁止上传扩展名为$ext的文件',\r\n");
	ViewBuilder.Append("                    'duplicate': '您已经选择了这个文件，请勿重复选择：$file'\r\n");
	ViewBuilder.Append("                }\r\n");
	ViewBuilder.Append("            });\r\n");
	ViewBuilder.Append("            $(\".MultiFile-remove\").live(\"click\", function () {\r\n");
	ViewBuilder.Append("                $(this).parent().remove();\r\n");
	ViewBuilder.Append("            });\r\n");
	ViewBuilder.Append("        })\r\n");
	ViewBuilder.Append("    </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("</body>\r\n");
	ViewBuilder.Append("</html>\r\n");
	if(iswrite==0)
	{
	Response.Write(ViewBuilder.ToString());
	}
	else if(iswrite==1)
	{
	Hashtable hash = new Hashtable();
	hash["errcode"] = 0;
	hash["errmsg"] ="";
	hash["html"]=ViewBuilder.ToString();
	FPResponse.WriteJson(hash);
	}
}
</script>
