<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="FangPage.WMS.Web.Controller.userprofile" %>
<%@ Import namespace="System.Collections.Generic" %>
<%@ Import namespace="FangPage.Common" %>
<%@ Import namespace="FangPage.MVC" %>
<%@ Import namespace="FangPage.WMS.Web" %>
<%@ Import namespace="FangPage.WMS" %>
<%@ Import namespace="FangPage.WMS.Model" %>
<%@ Import namespace="FangPage.WMS.Bll" %>
<script runat="server">
protected override void View()
{
	base.View();
	ViewBuilder.Append("<!DOCTYPE html>\r\n");
	ViewBuilder.Append("<html>\r\n");
	ViewBuilder.Append("<head>\r\n");
	ViewBuilder.Append("<meta content=\"text/html;charset=utf-8\" http-equiv=\"content-type\">\r\n");
	ViewBuilder.Append("<title>个人设置</title>\r\n");
	ViewBuilder.Append("	" + echo(meta) + "\r\n");
	ViewBuilder.Append("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
	ViewBuilder.Append("<meta name=\"renderer\" content=\"webkit\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/bootstrap.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/bootstrap-notify.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/bootstrap-modal.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/icomoon.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/bootstrap-editable.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"/oa/public/css/sidebar.css\">\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "jquery/jquery.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap.bootbox.min.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap.notify.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap-prompts.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap-modal.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap-modalmanager.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "jform/jquery.form.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"/oa/public/css/fp-bootstrap.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"/oa/public/css/base.css\">\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"/oa/public/css/global.css\">\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "modernizr/modernizr-2.6.1.min.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"/oa/public/js/util.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "mousewheel/jquery.mousewheel.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "nicescroll/jquery.nicescroll.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/avatar.css\">\r\n");
	ViewBuilder.Append("<meta name=\"GENERATOR\" content=\"MSHTML 9.00.8112.16599\">\r\n");

	if (ispost)
	{
	ViewBuilder.Append("    <script type=\"text/javascript\">\r\n");
	ViewBuilder.Append("        window.location.href = \"profile.aspx\";\r\n");
	ViewBuilder.Append("    </");
	ViewBuilder.Append("script>\r\n");
	}//end if
	ViewBuilder.Append("</head>\r\n");
	ViewBuilder.Append("<body style=\"overflow: hidden;\">\r\n");
	ViewBuilder.Append("<div id=\"container-scroller\">\r\n");
	ViewBuilder.Append("  <div>\r\n");
	ViewBuilder.Append("    <!--侧边栏-->\r\n");
	ViewBuilder.Append("<div class=\"sidebar\">\r\n");
	ViewBuilder.Append("    <div class=\"sidebar_logo T_icon\"><img src=\"" + echo(setupinfo.icon) + "\" style=\"width:64px;height:64px;\"></div>\r\n");
	ViewBuilder.Append("    <div class=\"sidebar_content T_bg\" style=\"padding-top:10px;\">\r\n");
	ViewBuilder.Append("        <ul id=\"sidebar_menu\" class=\"nav nav-list\">\r\n");
	ViewBuilder.Append("            <li>\r\n");
	ViewBuilder.Append("                <h4><a href=\"settings.aspx\"><i class=\"icon-windows8\"></i>系统设置</a></h4>\r\n");
	ViewBuilder.Append("            </li>\r\n");
	ViewBuilder.Append("            <li>\r\n");
	ViewBuilder.Append("                <h4><a href=\"profile.aspx\"><i class=\"icon-user\"></i>个人信息</a></h4>\r\n");
	ViewBuilder.Append("            </li>\r\n");
	ViewBuilder.Append("            <li>\r\n");
	ViewBuilder.Append("                <h4><a href=\"userpwd.aspx\"><i class=\"icon-lock\"></i>修改密码</a></h4>\r\n");
	ViewBuilder.Append("            </li>\r\n");
	ViewBuilder.Append("        </ul>\r\n");
	ViewBuilder.Append("    </div>\r\n");
	ViewBuilder.Append("    <div class=\"sidebar_buttons\"></div>\r\n");
	ViewBuilder.Append("</div>\r\n");
	ViewBuilder.Append("    <!--导航栏-->\r\n");
	ViewBuilder.Append("    <div style=\"margin-left: 180px;\">\r\n");
	ViewBuilder.Append("      <div class=\"td-nav\">\r\n");
	ViewBuilder.Append("        <table class=\"td-nav-table\">\r\n");
	ViewBuilder.Append("          <tbody>\r\n");
	ViewBuilder.Append("            <tr>\r\n");
	ViewBuilder.Append("              <td><span class=\"td-nav-title\">个人信息</span></td>\r\n");
	ViewBuilder.Append("              <td>\r\n");
	ViewBuilder.Append("                  <div class=\"pull-right\"><a style=\"margin-right:10px;margin-bottom:5px;\" id=\"btn_save\" class=\"btn btn-danger\" onclick='js:$(\"#profile-form\").submit()'>保存</a></div></td>\r\n");
	ViewBuilder.Append("            </tr>\r\n");
	ViewBuilder.Append("          </tbody>\r\n");
	ViewBuilder.Append("        </table>\r\n");
	ViewBuilder.Append("      </div>\r\n");
	ViewBuilder.Append("    </div>\r\n");
	ViewBuilder.Append("    <div style=\"margin-left: 180px;\" class=\"content\">\r\n");
	ViewBuilder.Append("      <div style=\"padding: 5px 10px;\">\r\n");
	ViewBuilder.Append("        <script type=\"text/javascript\">\r\n");
	ViewBuilder.Append("            function submitForm() {\r\n");
	ViewBuilder.Append("                var op = $('#avatar-op');\r\n");
	ViewBuilder.Append("                var bar = $('.bar', op);\r\n");
	ViewBuilder.Append("                var percent = $('.percent', op);\r\n");
	ViewBuilder.Append("                var progress = $('.progress', op);\r\n");
	ViewBuilder.Append("                var tip = $('.tip', op);\r\n");
	ViewBuilder.Append("                var edit = $('.edit', op);\r\n");
	ViewBuilder.Append("                var file = $('.file', op);\r\n");
	ViewBuilder.Append("                $('#avatar-form').ajaxForm({\r\n");
	ViewBuilder.Append("                    beforeSend: function () {\r\n");
	ViewBuilder.Append("                        var percentVal = '0%';\r\n");
	ViewBuilder.Append("                        bar.width(percentVal)\r\n");
	ViewBuilder.Append("                        percent.html(percentVal);\r\n");
	ViewBuilder.Append("                    },\r\n");
	ViewBuilder.Append("                    uploadProgress: function (event, position, total, percentComplete) {\r\n");
	ViewBuilder.Append("                        progress.show();\r\n");
	ViewBuilder.Append("                        edit.hide();\r\n");
	ViewBuilder.Append("                        var percentVal = percentComplete + '%';\r\n");
	ViewBuilder.Append("                        bar.width(percentVal)\r\n");
	ViewBuilder.Append("                        percent.html(percentVal);\r\n");
	ViewBuilder.Append("                    },\r\n");
	ViewBuilder.Append("                    success: function () {\r\n");
	ViewBuilder.Append("                        var percentVal = '100%';\r\n");
	ViewBuilder.Append("                        bar.width(percentVal)\r\n");
	ViewBuilder.Append("                        percent.html(percentVal);\r\n");
	ViewBuilder.Append("                    },\r\n");
	ViewBuilder.Append("                    complete: function (xhr) {\r\n");
	ViewBuilder.Append("                        data = $.parseJSON(xhr.responseText);\r\n");
	ViewBuilder.Append("                        if (data.type === \"false\") {\r\n");
	ViewBuilder.Append("                            tip.html('上传失败');\r\n");
	ViewBuilder.Append("                            $(\"#avatar\").append(data.msg);\r\n");
	ViewBuilder.Append("                            $('#avatar-img').attr({ \"src\": \"\" });\r\n");
	ViewBuilder.Append("                        } else {\r\n");
	ViewBuilder.Append("                            tip.html('上传成功');\r\n");
	ViewBuilder.Append("                            $('#avatar-img').attr({ \"src\": data.url });\r\n");
	ViewBuilder.Append("                        }\r\n");
	ViewBuilder.Append("                        tip.show();\r\n");
	ViewBuilder.Append("                        edit.hide();\r\n");
	ViewBuilder.Append("                        progress.hide();\r\n");
	ViewBuilder.Append("                        setTimeout(function () {\r\n");
	ViewBuilder.Append("                            tip.hide();\r\n");
	ViewBuilder.Append("                            edit.show();\r\n");
	ViewBuilder.Append("                            if ($(\"#tipMessage\").length > 0) {\r\n");
	ViewBuilder.Append("                                $(\"#tipMessage\").remove();\r\n");
	ViewBuilder.Append("                                $('#avatar-img').attr({ \"src\": data.url });\r\n");
	ViewBuilder.Append("                            }\r\n");
	ViewBuilder.Append("                        }, 2000);\r\n");
	ViewBuilder.Append("                    }\r\n");
	ViewBuilder.Append("                });\r\n");
	ViewBuilder.Append("                $('#avatar-form').submit();\r\n");
	ViewBuilder.Append("            }\r\n");
	ViewBuilder.Append("      </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("        <div class=\"row\">\r\n");
	ViewBuilder.Append("          <div style=\"width: 80px;\" class=\"span1\">\r\n");
	ViewBuilder.Append("            <form id=\"avatar-form\" class=\"form-vertical\" enctype=\"multipart/form-data\" method=\"post\" action=\"avatar.aspx\">\r\n");
	ViewBuilder.Append("              <div id=\"div_avatar\">\r\n");
	ViewBuilder.Append("                <img id=\"avatar-img\" src=\"" + echo(webpath) + "" + echo(fulluserinfo.avatar) + "\">\r\n");
	ViewBuilder.Append("                <div id=\"avatar-op\"><a class=\"edit\" name=\"edit\">更换头像\r\n");
	ViewBuilder.Append("                  <input id=\"user_avatar\" name=\"user_avatar\" type=\"hidden\">\r\n");
	ViewBuilder.Append("                  <input hidefocus=\"\" id=\"avatar\" onchange=\"submitForm()\" class=\"file\" name=\"avatar\" size=\"1\" type=\"file\">\r\n");
	ViewBuilder.Append("                  </a>\r\n");
	ViewBuilder.Append("                  <div style=\"display: none;\" class=\"progress\">\r\n");
	ViewBuilder.Append("                    <div class=\"bar\"></div>\r\n");
	ViewBuilder.Append("                    <div class=\"percent\">0%</div>\r\n");
	ViewBuilder.Append("                  </div>\r\n");
	ViewBuilder.Append("                  <div style=\"display: none;\" class=\"tip\"></div>\r\n");
	ViewBuilder.Append("                </div>\r\n");
	ViewBuilder.Append("              </div>\r\n");
	ViewBuilder.Append("            </form>\r\n");
	ViewBuilder.Append("          </div>\r\n");
	ViewBuilder.Append("          <div class=\"span5\" style=\"width:80%\">\r\n");
	ViewBuilder.Append("            <h2 style=\"line-height: 20px;\" id=\"user_name\">\r\n");
	ViewBuilder.Append("              <table class=\"detail-view table table-striped table-condensed\">\r\n");
	ViewBuilder.Append("                <tbody>\r\n");
	ViewBuilder.Append("                  <tr class=\"odd\">\r\n");
	ViewBuilder.Append("                    <th>姓名</th>\r\n");
	ViewBuilder.Append("                    <td><a href=\"#\" rel=\"User_user_name_3\" data-pk=\"3\">" + echo(fulluserinfo.realname) + "</a></td>\r\n");
	ViewBuilder.Append("                  </tr>\r\n");
	ViewBuilder.Append("                </tbody>\r\n");
	ViewBuilder.Append("              </table>\r\n");
	ViewBuilder.Append("            </h2>\r\n");
	ViewBuilder.Append("            <div style=\"height: 30px; line-height: 30px;\">所在部门：" + echo(DepartmentBll.GetUserDepartment(fulluserinfo.departid)) + "</div>\r\n");
	ViewBuilder.Append("          </div>\r\n");
	ViewBuilder.Append("        </div>\r\n");
	ViewBuilder.Append("        <form id=\"profile-form\" class=\"form-horizontal\" enctype=\"multipart/form-data\" method=\"post\" action=\"\">\r\n");
	ViewBuilder.Append("          <fieldset>\r\n");
	ViewBuilder.Append("            <legend>基本信息</legend>\r\n");
	ViewBuilder.Append("          </fieldset>\r\n");
	ViewBuilder.Append("          <div class=\"control-group \">\r\n");
	ViewBuilder.Append("            <label class=\"control-label\">登录名：</label>\r\n");
	ViewBuilder.Append("            <div class=\"controls\">\r\n");
	ViewBuilder.Append("              " + echo(fulluserinfo.username) + "\r\n");
	ViewBuilder.Append("            </div>\r\n");
	ViewBuilder.Append("          </div>\r\n");

	if (fulluserinfo.types!="")
	{
	ViewBuilder.Append("          <div class=\"control-group \">\r\n");
	ViewBuilder.Append("            <label class=\"control-label\">人员类型：</label>\r\n");
	ViewBuilder.Append("            <div class=\"controls\">\r\n");
	ViewBuilder.Append("              " + echo(fulluserinfo.usertype) + "\r\n");
	ViewBuilder.Append("            </div>\r\n");
	ViewBuilder.Append("          </div>\r\n");
	}//end if
	ViewBuilder.Append("          <div class=\"control-group \">\r\n");
	ViewBuilder.Append("            <label class=\"control-label\" for=\"realname\">姓名：</label>\r\n");
	ViewBuilder.Append("            <div class=\"controls\">\r\n");
	ViewBuilder.Append("              <input id=\"realname\" class=\"span5\" name=\"realname\" value=\"" + echo(fulluserinfo.realname) + "\" maxlength=\"50\" type=\"text\">\r\n");
	ViewBuilder.Append("            </div>\r\n");
	ViewBuilder.Append("          </div>\r\n");
	ViewBuilder.Append("          <div class=\"control-group \">\r\n");
	ViewBuilder.Append("            <label class=\"control-label\" for=\"sex\">性别：</label>\r\n");
	ViewBuilder.Append("            <div class=\"controls\">\r\n");
	ViewBuilder.Append("              <select id=\"sex\" class=\"span2\" name=\"sex\">\r\n");
	ViewBuilder.Append("                <option "+(fulluserinfo.sex=="男"?"selected":"")+" value=\"男\">男</option>\r\n");
	ViewBuilder.Append("                <option "+(fulluserinfo.sex=="女"?"selected":"")+" value=\"女\">女</option>\r\n");
	ViewBuilder.Append("                <option "+(fulluserinfo.sex==""?"selected":"")+" value=\"\">未知</option>\r\n");
	ViewBuilder.Append("              </select>\r\n");
	ViewBuilder.Append("            </div>\r\n");
	ViewBuilder.Append("          </div>\r\n");
	ViewBuilder.Append("          <fieldset>\r\n");
	ViewBuilder.Append("            <legend>联系方式</legend>\r\n");
	ViewBuilder.Append("          </fieldset>\r\n");
	ViewBuilder.Append("          <div class=\"control-group \">\r\n");
	ViewBuilder.Append("            <label class=\"control-label\" for=\"phone\">固定电话：</label>\r\n");
	ViewBuilder.Append("            <div class=\"controls\">\r\n");
	ViewBuilder.Append("              <input id=\"phone\" class=\"span5\" name=\"phone\" value=\"" + echo(fulluserinfo.phone) + "\" maxlength=\"50\" type=\"text\">\r\n");
	ViewBuilder.Append("            </div>\r\n");
	ViewBuilder.Append("          </div>\r\n");
	ViewBuilder.Append("          <div class=\"control-group \">\r\n");
	ViewBuilder.Append("            <label class=\"control-label\" for=\"UserProfile_mobile\">手机号码：</label>\r\n");
	ViewBuilder.Append("            <div class=\"controls\">\r\n");
	ViewBuilder.Append("              <input id=\"mobile\" class=\"span5\" name=\"mobile\" maxlength=\"50\" value=\"" + echo(fulluserinfo.mobile) + "\" type=\"text\">\r\n");
	ViewBuilder.Append("            </div>\r\n");
	ViewBuilder.Append("          </div>\r\n");
	ViewBuilder.Append("          <div class=\"control-group \">\r\n");
	ViewBuilder.Append("            <label class=\"control-label\" for=\"UserProfile_email\">邮箱地址：</label>\r\n");
	ViewBuilder.Append("            <div class=\"controls\">\r\n");
	ViewBuilder.Append("              <input id=\"email\" class=\"span5\" name=\"email\" maxlength=\"50\" value=\"" + echo(fulluserinfo.email) + "\" type=\"text\">\r\n");
	ViewBuilder.Append("            </div>\r\n");
	ViewBuilder.Append("          </div>\r\n");
	ViewBuilder.Append("          <fieldset>\r\n");
	ViewBuilder.Append("            <legend>详细信息</legend>\r\n");
	ViewBuilder.Append("          </fieldset>\r\n");
	ViewBuilder.Append("          <div class=\"control-group \">\r\n");
	ViewBuilder.Append("            <label class=\"control-label\" for=\"UserProfile_email\">工作岗位：</label>\r\n");
	ViewBuilder.Append("            <div class=\"controls\">\r\n");
	ViewBuilder.Append("              <input id=\"company\" class=\"span5\" name=\"company\" maxlength=\"50\" value=\"" + echo(fulluserinfo.company) + "\" type=\"text\">\r\n");
	ViewBuilder.Append("            </div>\r\n");
	ViewBuilder.Append("          </div>\r\n");
	ViewBuilder.Append("          <div class=\"control-group \">\r\n");
	ViewBuilder.Append("            <label class=\"control-label\" for=\"UserProfile_email\">技术职称：</label>\r\n");
	ViewBuilder.Append("            <div class=\"controls\">\r\n");
	ViewBuilder.Append("              <input id=\"position\" class=\"span5\" name=\"position\" maxlength=\"50\" value=\"" + echo(fulluserinfo.position) + "\" type=\"text\">\r\n");
	ViewBuilder.Append("            </div>\r\n");
	ViewBuilder.Append("          </div>\r\n");
	ViewBuilder.Append("        </form>\r\n");
	ViewBuilder.Append("      </div>\r\n");
	ViewBuilder.Append("    </div>\r\n");
	ViewBuilder.Append("  </div>\r\n");
	ViewBuilder.Append("</div>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "bootstrap/js/bootstrap-editable.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\">\r\n");
	ViewBuilder.Append("    jQuery(function ($) {\r\n");
	ViewBuilder.Append("        $(document).ready(function () {\r\n");
	ViewBuilder.Append("            $(\"#sidebar_menu a[href$=\\\"profile.aspx\\\"]\").parents(\"li\").addClass(\"active\");\r\n");
	ViewBuilder.Append("        });\r\n");
	ViewBuilder.Append("        $('a[rel=User_user_name_3]').editable({\r\n");
	ViewBuilder.Append("            'datepicker': { 'language': 'zh' }, 'type': 'text', 'url': '" + echo(apppath) + "settings/updateusername.aspx', 'name': 'user_name', 'title': '输入 姓名', 'placement': 'bottom', 'emptytext': '未设置', 'validate': function (value) {\r\n");
	ViewBuilder.Append("                if ($.trim(value) == \"\") return \"用户姓名不能为空\";\r\n");
	ViewBuilder.Append("            }\r\n");
	ViewBuilder.Append("        });\r\n");
	ViewBuilder.Append("        $(window).resize(function () {\r\n");
	ViewBuilder.Append("            var height = $(window).height();\r\n");
	ViewBuilder.Append("            $(\".sidebar\").height(height);\r\n");
	ViewBuilder.Append("            if ($(\".td-nav\").length > 0) {\r\n");
	ViewBuilder.Append("                $(\".content\").height(height - $(\".td-nav\").height());\r\n");
	ViewBuilder.Append("            } else {\r\n");
	ViewBuilder.Append("                $(\".content\").height(height);\r\n");
	ViewBuilder.Append("            }\r\n");
	ViewBuilder.Append("        });\r\n");
	ViewBuilder.Append("        $(window).trigger(\"resize\"); $(\".content\").niceScroll({ cursorcolor: \"#ccc\", cursoropacitymin: 1, cursorwidth: 8 }); if ($(\".sidebar\").find(\".ztree\").length > 0) {\r\n");
	ViewBuilder.Append("            $(\".sidebar\").niceScroll({ cursorcolor: \"#ccc\"});\r\n");
	ViewBuilder.Append("        } else {\r\n");
	ViewBuilder.Append("            $(\".sidebar\").niceScroll({ cursorcolor: \"#ccc\", horizrailenabled: false });\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("    });\r\n");
	ViewBuilder.Append("</");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("</body>\r\n");
	ViewBuilder.Append("</html>\r\n");
	if(iswrite==0)
	{
	Response.Write(ViewBuilder.ToString());
	}
	else if(iswrite==1)
	{
	Hashtable hash = new Hashtable();
	hash["errcode"] = 0;
	hash["errmsg"] ="";
	hash["html"]=ViewBuilder.ToString();
	FPResponse.WriteJson(hash);
	}
}
</script>
