<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="FP_NTKO.index" %>
<%@ Import namespace="System.Collections.Generic" %>
<%@ Import namespace="FangPage.Common" %>
<%@ Import namespace="FangPage.MVC" %>
<%@ Import namespace="FP_NTKO" %>
<script runat="server">
protected override void View()
{
	/*方配软件技术有限责任公司(WMS框架)，官方网站：http://www.fangpage.com  QQ:12677206*/
	base.View();
	ViewBuilder.Append("<!--[if IE]>\r\n");
	ViewBuilder.Append("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
	ViewBuilder.Append("<![endif]-->\r\n");
	ViewBuilder.Append("<!DOCTYPE html>\r\n");
	ViewBuilder.Append("<html>\r\n");
	ViewBuilder.Append("<head>\r\n");
	ViewBuilder.Append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
	ViewBuilder.Append("<title>\r\n");

	if (op==1)
	{
	ViewBuilder.Append("    Office 文档在线编辑\r\n");
	}
	else
	{
	ViewBuilder.Append("    Office 文档在线阅读\r\n");
	}//end if
	ViewBuilder.Append("</title>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"" + echo(plupath) + "bootstrap/css/bootstrap.css\"></link>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"/oa/public/css/document.css\"></link>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"/oa/public/css/workflow.turn.css\"></link>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"/oa/public/css/selector.css\"></link>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "jquery/jquery.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"" + echo(plupath) + "modernizr/modernizr-2.6.1.min.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"/oa/public/css/fp-bootstrap.css\"></link>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"/oa/public/css/base.css\"></link>\r\n");
	ViewBuilder.Append("<link rel=\"stylesheet\" type=\"text/css\" href=\"/oa/public/css/global.css\"></link>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\" src=\"ntkoocx.js\"></");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("<script type=\"text/jscript\">\r\n");
	ViewBuilder.Append("    function myload() {\r\n");
	ViewBuilder.Append("        TANGER_OCX_SetInfo();\r\n");
	ViewBuilder.Append("        TANGER_OCX_OpenDoc('readdisk.aspx?aid=" + echo(aid) + "&name=" + echo(attachinfo.name) + "');\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    function SelSign() {\r\n");
	ViewBuilder.Append("        var SelSign = document.getElementById(\"SelSign\");\r\n");
	ViewBuilder.Append("        if (SelSign.style.display == \"\")\r\n");
	ViewBuilder.Append("            SelSign.style.display = \"none\";\r\n");
	ViewBuilder.Append("        else\r\n");
	ViewBuilder.Append("            SelSign.style.display = \"\";\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    //保留痕迹\r\n");
	ViewBuilder.Append("    function MY_SetMarkModify(flag) {\r\n");
	ViewBuilder.Append("        TANGER_OCX_SetMarkModify(flag);\r\n");
	ViewBuilder.Append("        if (flag) {\r\n");
	ViewBuilder.Append("            mflag1.style.fontWeight = \"bold\";\r\n");
	ViewBuilder.Append("            mflag2.style.fontWeight = \"\";\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("        else {\r\n");
	ViewBuilder.Append("            mflag1.style.fontWeight = \"\";\r\n");
	ViewBuilder.Append("            mflag2.style.fontWeight = \"bold\";\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("        TANGER_OCX_OBJ.focus();\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    //显示痕迹\r\n");
	ViewBuilder.Append("    function MY_ShowRevisions(flag) {\r\n");
	ViewBuilder.Append("        TANGER_OCX_ShowRevisions(flag);\r\n");
	ViewBuilder.Append("        if (flag) {\r\n");
	ViewBuilder.Append("            sflag1.style.fontWeight = \"bold\";\r\n");
	ViewBuilder.Append("            sflag2.style.fontWeight = \"\";\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("        else {\r\n");
	ViewBuilder.Append("            sflag1.style.fontWeight = \"\";\r\n");
	ViewBuilder.Append("            sflag2.style.fontWeight = \"bold\";\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    function insertRedHeadFromUrl(headFileURL) {\r\n");
	ViewBuilder.Append("        try {\r\n");
	ViewBuilder.Append("            if (TANGER_OCX_OBJ.doctype != 1)//TANGER_OCX_OBJ.doctype=1为word文档\r\n");
	ViewBuilder.Append("            { return; }\r\n");
	ViewBuilder.Append("            TANGER_OCX_OBJ.ActiveDocument.Application.Selection.HomeKey(6, 0); //光标移动到文档开头\r\n");
	ViewBuilder.Append("            //TANGER_OCX_OBJ.addtemplatefromurl(headFileURL);//在光标位置插入红头文档\r\n");
	ViewBuilder.Append("            //选择对象当前文档的所有内容\r\n");
	ViewBuilder.Append("            var curSel = TANGER_OCX_OBJ.ActiveDocument.Application.Selection;\r\n");
	ViewBuilder.Append("            TANGER_OCX_SetMarkModify(false);\r\n");
	ViewBuilder.Append("            curSel.WholeStory();\r\n");
	ViewBuilder.Append("            curSel.Cut();\r\n");
	ViewBuilder.Append("            //插入模板\r\n");
	ViewBuilder.Append("            //URL=\"/module/word_model/view/get.aspx?MODEL=\"+URL;\r\n");
	ViewBuilder.Append("            TANGER_OCX_OBJ.AddTemplateFromURL(headFileURL);\r\n");
	ViewBuilder.Append("            var BookMarkName = \"zhengwen\";\r\n");
	ViewBuilder.Append("            if (!TANGER_OCX_OBJ.ActiveDocument.BookMarks.Exists(BookMarkName)) {\r\n");
	ViewBuilder.Append("                alert(\"Word 模板中不存在名称为：\\\"\" + BookMarkName + \"\\\"的书签！\\n关于套红模版制作，请咨询技术支持人员。\");\r\n");
	ViewBuilder.Append("                return;\r\n");
	ViewBuilder.Append("            }\r\n");
	ViewBuilder.Append("            var bkmkObj = TANGER_OCX_OBJ.ActiveDocument.BookMarks(BookMarkName);\r\n");
	ViewBuilder.Append("            var saverange = bkmkObj.Range\r\n");
	ViewBuilder.Append("            saverange.Paste();\r\n");
	ViewBuilder.Append("            TANGER_OCX_OBJ.ActiveDocument.Bookmarks.Add(BookMarkName, saverange);\r\n");
	ViewBuilder.Append("            TANGER_OCX_SetMarkModify(true);\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("        catch (err) {\r\n");
	ViewBuilder.Append("            alert(\"错误：\" + err.number + \":\" + err.description);\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    function openTemplateFileFromUrl(templateUrl) {\r\n");
	ViewBuilder.Append("        TANGER_OCX_OBJ.openFromUrl(templateUrl);\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    function MyAddSign() {\r\n");
	ViewBuilder.Append("        var sltSign = document.getElementById(\"sltSign\");\r\n");
	ViewBuilder.Append("        if (sltSign != null) {\r\n");
	ViewBuilder.Append("            if (sltSign.length == 1) {\r\n");
	ViewBuilder.Append("                alert(\"系统未定义印章！\");\r\n");
	ViewBuilder.Append("                return false;\r\n");
	ViewBuilder.Append("            }\r\n");
	ViewBuilder.Append("            if (sltSign.value == \"\") {\r\n");
	ViewBuilder.Append("                alert(\"请选择您要加盖的电子印章！\");\r\n");
	ViewBuilder.Append("                return false;\r\n");
	ViewBuilder.Append("            }\r\n");
	ViewBuilder.Append("            AddSignFromURL(sltSign.value);\r\n");
	ViewBuilder.Append("            return true;\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("    }\r\n");
	ViewBuilder.Append("    </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("</head>\r\n");
	ViewBuilder.Append("<body style=\"overflow: hidden;\" onload=\"myload();\">\r\n");
	ViewBuilder.Append("<form id=\"myForm\" name=\"myForm\" method=\"post\" enctype=\"multipart/form-data\" action=\"uploaddisk.aspx\">\r\n");
	ViewBuilder.Append("<!--导航栏-->\r\n");
	ViewBuilder.Append("<div id=\"page-navbar\">\r\n");
	ViewBuilder.Append("  <div class=\"td-nav\">\r\n");
	ViewBuilder.Append("    <table class=\"td-nav-table\">\r\n");
	ViewBuilder.Append("      <tbody>\r\n");
	ViewBuilder.Append("        <tr>\r\n");
	ViewBuilder.Append("          <td style=\"height:30px;\">\r\n");
	ViewBuilder.Append("            <span class=\"td-nav-title\" style=\"display: block;\">" + echo(attachinfo.name,70)+ "</span>\r\n");
	ViewBuilder.Append("          </td>\r\n");
	ViewBuilder.Append("          <td>\r\n");
	ViewBuilder.Append("              <div class=\"pull-right\" style=\"margin-top:5px;\">\r\n");
	ViewBuilder.Append("                  <a style=\"margin-right:3px;\" class=\"btn btn-danger\" onclick=\"TANGER_OCX_SaveEditToServerDisk(0);\">保存</a>\r\n");
	ViewBuilder.Append("                  <a style=\"margin-right:3px;\" class=\"btn btn-primary\" href=\"" + echo(plupath) + "attach/download.aspx?aid=" + echo(aid) + "\">下载</a>\r\n");
	ViewBuilder.Append("                  <a onclick=\"window.close();\" style=\"margin-right:3px;\" class=\"btn\">关闭</a>\r\n");
	ViewBuilder.Append("              </div>\r\n");
	ViewBuilder.Append("          </td>\r\n");
	ViewBuilder.Append("        </tr>\r\n");
	ViewBuilder.Append("      </tbody>\r\n");
	ViewBuilder.Append("    </table>\r\n");
	ViewBuilder.Append("  </div>\r\n");
	ViewBuilder.Append("</div>\r\n");
	ViewBuilder.Append("<div id=\"container-scroller\">\r\n");
	ViewBuilder.Append("    <object id=\"TANGER_OCX\" classid=\"clsid:C9BC4DFF-4248-4a3c-8A49-63A7D317F404\" codebase=\"" + echo(plupath) + "ntko/OfficeControl.cab#version=4,0,1,2\" width=\"100%\" height=\"100%\" viewastext=\"\">\r\n");
	ViewBuilder.Append("        <param name=\"MakerCaption\" value=\"中国兵器工业信息中心通达科技\">\r\n");
	ViewBuilder.Append("        <param name=\"MakerKey\" value=\"86A1BE7CFEC466B6186E5425AFABB417B6016D68\">\r\n");
	ViewBuilder.Append("        <param name=\"ProductCaption\" value=\"Office Anywhere 2008\">\r\n");
	ViewBuilder.Append("        <param name=\"ProductKey\" value=\"0BB273749DB6667F429D0E1862B4B852A7D557BE\">\r\n");
	ViewBuilder.Append("        <param name=\"_ExtentX\" value=\"18071\">\r\n");
	ViewBuilder.Append("        <param name=\"_ExtentY\" value=\"20981\">\r\n");
	ViewBuilder.Append("        <param name=\"BorderColor\" value=\"14402205\">\r\n");
	ViewBuilder.Append("        <param name=\"BackColor\" value=\"-2147483643\">\r\n");
	ViewBuilder.Append("        <param name=\"ForeColor\" value=\"-2147483640\">\r\n");
	ViewBuilder.Append("        <param name=\"TitlebarColor\" value=\"14402205\">\r\n");
	ViewBuilder.Append("        <param name=\"TitlebarTextColor\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"BorderStyle\" value=\"1\">\r\n");
	ViewBuilder.Append("        <param name=\"Titlebar\" value=\"1\">\r\n");
	ViewBuilder.Append("        <param name=\"Caption\" value=\"Office文档在线编辑\">\r\n");
	ViewBuilder.Append("        <param name=\"IsShowToolMenu\" value=\"1\">\r\n");
	ViewBuilder.Append("        <param name=\"IsNoCopy\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"IsHiddenOpenURL\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"MaxUploadSize\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"Menubar\" value=\"1\">\r\n");
	ViewBuilder.Append("        <param name=\"Statusbar\" value=\"1\">\r\n");
	ViewBuilder.Append("        <param name=\"FileNew\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"FileOpen\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"FileClose\" value=\"-1\">\r\n");
	ViewBuilder.Append("        <param name=\"FileSave\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"FileSaveAs\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"FilePrint\" value=\"-1\">\r\n");
	ViewBuilder.Append("        <param name=\"FilePrintPreview\" value=\"-1\">\r\n");
	ViewBuilder.Append("        <param name=\"FilePageSetup\" value=\"-1\">\r\n");
	ViewBuilder.Append("        <param name=\"FileProperties\" value=\"-1\">\r\n");
	ViewBuilder.Append("        <param name=\"IsStrictNoCopy\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"IsUseUTF8URL\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"MenubarColor\" value=\"-2147483643\">\r\n");
	ViewBuilder.Append("        <param name=\"IsUseControlAgent\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"IsUseUTF8Data\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"IsSaveDocExtention\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"IsDirectConnect\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"SignCursorType\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"IsResetToolbarsOnOpen\" value=\"0\">\r\n");
	ViewBuilder.Append("        <param name=\"IsSaveDataIfHasVDS\" value=\"0\">\r\n");
	ViewBuilder.Append("        <span style=\"color: red\">不能装载文档编辑控件。请选用IE浏览器模式来进行编辑。</span>\r\n");
	ViewBuilder.Append("    </object>\r\n");
	ViewBuilder.Append("    <!-- OnDocumentClosed and OnDocumentOpened -->\r\n");
	ViewBuilder.Append("    <script type=\"text/javascript\" for=\"TANGER_OCX\" event=\"OnDocumentClosed()\">\r\n");
	ViewBuilder.Append("        TANGER_OCX_OnDocumentClosed();\r\n");
	ViewBuilder.Append("    </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("    <script type=\"text/javascript\" for=\"TANGER_OCX\" event=\"OnDocumentOpened(TANGER_OCX_str,TANGER_OCX_obj)\">\r\n");
	ViewBuilder.Append("        TANGER_OCX_OnDocumentOpened(TANGER_OCX_str, TANGER_OCX_obj);\r\n");
	ViewBuilder.Append("    </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("    <script type=\"text/javascript\" for=\"TANGER_OCX\" event=\"AfterOpenFromURL(doc)\">\r\n");
	ViewBuilder.Append("        //该事件在BeginOpenFromURL方法执行完毕之后被触发。\r\n");
	ViewBuilder.Append("    </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("    <script type=\"text/javascript\" for=\"TANGER_OCX\" event=\"OnFileCommand(cmd,canceled)\">\r\n");
	ViewBuilder.Append("        if (cmd == 3) //user has clicked on file save menu or button\r\n");
	ViewBuilder.Append("        {\r\n");
	ViewBuilder.Append("            //save to server\r\n");
	ViewBuilder.Append("            //cancel default process\r\n");
	ViewBuilder.Append("            //TANGER_OCX_SaveEditToServerDisk();\r\n");
	ViewBuilder.Append("            //document.all(\"TANGER_OCX\").CancelLastCommand = true;\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("    </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("    <script type=\"text/javascript\" for=\"TANGER_OCX\" event=\"OnSignSelect(issign,signinfo)\">\r\n");
	ViewBuilder.Append("        if (issign) {\r\n");
	ViewBuilder.Append("            TANGER_OCX_OBJ.SetReadOnly(true);\r\n");
	ViewBuilder.Append("            TANGER_OCX_OBJ.SetReadOnly(false);\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("        else {\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("    </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("    <script type=\"text/javascript\">\r\n");
	ViewBuilder.Append("        var close_op_flag = 0;\r\n");
	ViewBuilder.Append("        window.onbeforeunload = function close_doc() {\r\n");
	ViewBuilder.Append("            if (TANGER_OCX_op == \"1\") {\r\n");
	ViewBuilder.Append("                try {\r\n");
	ViewBuilder.Append("                    document.all(\"TANGER_OCX\").setAttribute(\"IsNoCopy\", false);\r\n");
	ViewBuilder.Append("                    if (close_op_flag != 1) {\r\n");
	ViewBuilder.Append("                        msg = '是否保存对  \\'" + echo(attachinfo.name) + "\\'  的修改？';\r\n");
	ViewBuilder.Append("                        if (window.confirm(msg))\r\n");
	ViewBuilder.Append("                            TANGER_OCX_SaveEditToServerDisk(0);\r\n");
	ViewBuilder.Append("                    }\r\n");
	ViewBuilder.Append("                }\r\n");
	ViewBuilder.Append("                catch (err) { };\r\n");
	ViewBuilder.Append("            }\r\n");
	ViewBuilder.Append("        }\r\n");
	ViewBuilder.Append("    </");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("   <!-- TANGER_OCX_op 1编辑,0阅读-->\r\n");
	ViewBuilder.Append("    <input type=\"hidden\" name=\"TANGER_OCX_op\" value=\"1\">\r\n");
	ViewBuilder.Append("    <input type=\"hidden\" name=\"TANGER_OCX_attachid\" value=\"\">\r\n");
	ViewBuilder.Append("    <input type=\"hidden\" name=\"TANGER_OCX_attachmentid\" value=\"" + echo(aid) + "\">\r\n");
	ViewBuilder.Append("    <input type=\"hidden\" name=\"TANGER_OCX_filename\" value=\"" + echo(attachinfo.name) + "\">\r\n");
	ViewBuilder.Append("    <input type=\"hidden\" name=\"TANGER_OCX_username\" value=\"" + echo(user.realname) + "\">\r\n");
	ViewBuilder.Append("</div>\r\n");
	ViewBuilder.Append("</form>\r\n");
	ViewBuilder.Append("<script type=\"text/javascript\">\r\n");
	ViewBuilder.Append("    $(function () {\r\n");
	ViewBuilder.Append("        $(window).resize(function () {\r\n");
	ViewBuilder.Append("            var height = $(window).height();\r\n");
	ViewBuilder.Append("            $(\"#container-scroller\").height(height - $(\".td-nav\").height());\r\n");
	ViewBuilder.Append("        });\r\n");
	ViewBuilder.Append("        $(window).trigger(\"resize\");\r\n");
	ViewBuilder.Append("    });\r\n");
	ViewBuilder.Append("</");
	ViewBuilder.Append("script>\r\n");
	ViewBuilder.Append("</body>\r\n");
	ViewBuilder.Append("</html>\r\n");
	Response.Write(ViewBuilder.ToString());
}
</script>
