document.write('<!-- 用来产生编辑状态的ActiveX控件的JS脚本-->   ');
document.write('<!-- 因为微软的ActiveX新机制，需要一个外部引入的js-->   ');
document.write('<object id="TANGER_OCX" classid="clsid:C9BC4DFF-4248-4a3c-8A49-63A7D317F404"    ');
document.write('codebase="/module/OC/OfficeControl.cab#version=4,0,1,2" width="100%" height="100%">   ');
document.write('<param name="MakerCaption" value="中国兵器工业信息中心通达科技">   ');
document.write('<param name="MakerKey" value="86A1BE7CFEC466B6186E5425AFABB417B6016D68">   ');
document.write('<param name="ProductCaption" value="Office Anywhere 2008">   ');
document.write('<param name="ProductKey" value="0BB273749DB6667F429D0E1862B4B852A7D557BE">   ');
document.write('<param name="BorderStyle" value="1">   ');
document.write('<param name="BorderColor" value="14402205">   ');
document.write('<param name="TitlebarColor" value="15658734">   ');
document.write('<param name="TitlebarTextColor" value="0">   ');
document.write('<param name="Caption" value="Office文档在线编辑');
document.write('<param name="IsUseUTF8URL" value="-1">   ');
document.write('<param name="IsUseUTF8DATA" value="-1">   ');
document.write('<param name="MaxUploadSize" value="10000000">   ');
document.write('<param name="MenubarColor" value="14402205">   ');
document.write('<param name="MenuButtonColor" VALUE="16180947">   ');
document.write('<param name="MenuBarStyle" value="3">   ');
document.write('<param name="MenuButtonStyle" value="7">   ');
document.write('<SPAN STYLE="color:red">不能装载文档控件。请在检查浏览器的选项中检查浏览器的安全设置。</SPAN>   ');
document.write('</object>   ');